// ADXB_CopyExtraBufMono
// ADXB_CopyExtraBufSte
// ADXB_Create
// ADXB_DecodeHeader
// ADXB_DecodeHeaderAdx
// adxb_DefAddWr
// adxb_DefGetWr
// ADXB_Destroy
// ADXB_EndDecode
// ADXB_EntryAddWrFunc
// ADXB_EntryData
// ADXB_EntryGetWrFunc
// ADXB_EvokeDecode
// ADXB_EvokeExpandMono
// ADXB_EvokeExpandSte
// ADXB_ExecHndl
// ADXB_ExecOneAdx
// ADXB_ExecServer
// ADXB_GetAdxpd
// ADXB_GetBlkLen
// ADXB_GetBlkSmpl
// ADXB_GetCof
// ADXB_GetDecDtLen
// ADXB_GetDecNumSmpl
// ADXB_GetFmtBps
// ADXB_GetFormat
// ADXB_GetLpEndOfst
// ADXB_GetLpEndPos
// ADXB_GetLpInsNsmpl
// ADXB_GetLpStartOfst
// ADXB_GetLpStartPos
// ADXB_GetNumChan
// ADXB_GetNumLoop
// ADXB_GetOutBps
// ADXB_GetPcmBuf
// ADXB_GetSfreq
// ADXB_GetStat
// ADXB_GetTotalNumSmpl
// ADXB_Init
// ADXB_Reset
// ADXB_Start
// ADXB_Stop
// memcpy2