// DTX_CallUrpc
// DTX_Close
// DTX_Create
// dtx_create_rmt
// dtx_def_rcvcbf
// dtx_def_sndcbf
// DTX_Destroy
// dtx_destroy_rmt
// DTX_ExecHndl
// DTX_ExecServer
// DTX_Finish
// DTX_Init
// DTX_Open
// dtx_rpc_func
// DTX_SetRcvCbf
// DTX_SetSndCbf
// dtx_svr_proc