// dvci_alloc
// dvci_call_errfn
// dvci_conv_fname
// dvci_free
// dvci_to_large_to_yen
// dvci_wait
// dvCiClose
// dvCiEntryErrFunc
// dvCiExecHndl
// dvCiExecServer
// dvCiGetFileSize
// dvCiGetInterface
// dvCiGetNumTr
// dvCiGetSctLen
// dvCiGetStat
// dvCiOpen
// dvCiReqRd
// dvCiSeek
// dvCiStopTr
// dvCiTell
// dvg_ci_build
