// SJMEM_CreateRmt
// SJRBF_CreateRmt
// SJRMT_Destroy
// SJRMT_Finish
// SJRMT_GetChunk
// SJRMT_GetNumData
// SJRMT_GetUuid
// SJRMT_Init
// SJRMT_IsGetChunk
// SJRMT_PutChunk
// SJRMT_Reset
// SJRMT_UngetChunk
// SJUNI_CreateRmt