#ifndef _EFFSUB1_H_
#define _EFFSUB1_H_

#include "types.h"

/*typedef struct _anon0;
typedef struct npobj;
typedef struct _anon1;
typedef struct _anon2;
typedef struct _anon3;
typedef struct _anon4;
typedef struct _anon5;
typedef struct _anon6;
typedef struct _anon7;
typedef struct _anon8;
typedef struct _anon9;
typedef struct _anon10;
typedef struct _anon11;
typedef struct _anon12;
typedef struct BH_PWORK;
typedef struct _anon13;
typedef struct _anon14;
typedef struct _anon15;
typedef struct _anon16;
typedef struct _anon17;
typedef struct _anon18;
typedef struct _anon19;
typedef struct _anon20;
typedef struct _anon21;
typedef struct _anon22;
typedef struct _anon23;
typedef struct _anon24;
typedef struct _anon25;
typedef struct _anon26;
typedef union _anon27;
typedef struct _anon28;
typedef struct _anon29;
typedef struct _anon30;
typedef struct _anon31;
typedef struct _anon32;
typedef struct _anon33;
typedef struct _anon34;
typedef struct _anon35;
typedef struct _anon36;
typedef struct _anon37;
typedef struct _anon38;
typedef struct _anon39;
typedef struct _anon40;
typedef struct _anon41;
typedef struct _anon42;
typedef struct _anon43;
typedef struct _anon44;
typedef struct _anon45;
typedef struct _anon46;
typedef struct _anon47;
typedef struct _anon48;
typedef struct _anon49;
typedef struct _anon50;
typedef struct _anon51;
typedef struct _anon52;
typedef struct _anon53;
typedef struct _anon54;
typedef struct _anon55;
typedef struct _anon56;

typedef void(*type_84)(_anon0*);
typedef void(*type_90)(_anon0*);
typedef void(*type_100)(_anon0*);
typedef void(*type_131)(_anon0*);
typedef void(*type_149)(void*);
typedef void(*type_156)(_anon0*);
typedef void(*type_182)(_anon0*);
typedef void(*type_200)(_anon0*);
typedef void(*type_205)(_anon0*);
typedef void(*type_220)(_anon0*);

typedef _anon8 type_0[13];
typedef float type_1[16];
typedef unsigned int type_2[4];
typedef _anon8 type_3[9];
typedef _anon0* type_4[512];
typedef _anon0* type_5[32];
typedef _anon8 type_6[11];
typedef _anon8 type_7[8];
typedef _anon4* type_8[16];
typedef _anon8 type_9[20];
typedef _anon8 type_10[11];
typedef _anon0* type_11[32];
typedef _anon0* type_12[512];
typedef _anon4* type_13[16][16];
typedef _anon4* type_14[16][16][100];
typedef char type_15[8];
typedef _anon0* type_16[32];
typedef _anon0* type_17[512];
typedef _anon4* type_18[1300];
typedef char type_19[32];
typedef float type_20[32];
typedef _anon8 type_21[9];
typedef _anon0* type_22[512];
typedef _anon4* type_23[200];
typedef short type_24[32];
typedef _anon30 type_25[1];
typedef _anon8 type_26[12];
typedef short type_27[9];
typedef _anon0* type_28[128];
typedef unsigned int type_29[1];
typedef _anon8 type_30[8];
typedef _anon5 type_31[4];
typedef _anon3 type_32[256];
typedef _anon4* type_33[8];
typedef _anon8 type_34[5];
typedef int* type_35[16];
typedef _anon8 type_36[16];
typedef _anon8 type_37[6];
typedef _anon0* type_38[128];
typedef _anon55 type_39[16];
typedef npobj* type_40[16];
typedef _anon8 type_41[16];
typedef _anon0* type_42[128];
typedef int type_43[4];
typedef _anon4* type_44[16];
typedef unsigned int type_45[4];
typedef float type_46[4];
typedef _anon17 type_47[16];
typedef _anon8 type_48[15];
typedef _anon8 type_49[5];
typedef _anon0* type_50[512];
typedef float type_51[4];
typedef _anon8 type_52[14];
typedef char type_53[256];
typedef float type_54[4];
typedef _anon8 type_55[4];
typedef _anon5 type_56[4];
typedef float type_57[4];
typedef _anon8 type_58[4];
typedef _anon8 type_59[7];
typedef _anon8 type_60[11];
typedef float type_61[4];
typedef float type_62[4];
typedef _anon10* type_63[128];
typedef BH_PWORK type_64[0];
typedef _anon22 type_65[0];
typedef float type_66[3];
typedef _anon8 type_67[14];
typedef unsigned char type_68[64];
typedef float type_69[3][20];
typedef _anon0 type_70[0];
typedef float type_71[3];
typedef float type_72[3][20];
typedef _anon37 type_73[0];
typedef _anon8 type_74[6];
typedef int type_75[2];
typedef float type_76[3];
typedef float type_77[3][20];
typedef _anon8 type_78[4];
typedef _anon8 type_79[6];
typedef _anon8 type_80[9];
typedef char type_81[8];
typedef _anon8 type_82[3];
typedef float type_83[3];
typedef float type_85[3][20];
typedef _anon8 type_86[11];
typedef _anon8 type_87[4];
typedef _anon8 type_88[15];
typedef void* type_89[2];
typedef _anon8 type_91[1];
typedef _anon8 type_92[16];
typedef _anon8 type_93[4];
typedef _anon8 type_94[4][2];
typedef _anon4* type_95[256];
typedef _anon8 type_96[13];
typedef _anon8 type_97[11];
typedef int type_98[4];
typedef unsigned char* type_99[256];
typedef _anon5 type_101[4];
typedef _anon8 type_102[8];
typedef unsigned int type_103[2];
typedef short type_104[256];
typedef _anon8 type_105[9];
typedef _anon38 type_106[4];
typedef _anon40 type_107[4];
typedef float type_108[3];
typedef short type_109[256];
typedef int type_110[3];
typedef _anon8 type_111[9];
typedef int type_112[8];
typedef _anon27 type_113[4];
typedef _anon8 type_114[9][2];
typedef float type_115[3];
typedef _anon4* type_116[256];
typedef _anon8 type_117[8];
typedef _anon8 type_118[9];
typedef _anon15 type_119[256];
typedef _anon8 type_120[9];
typedef _anon30 type_121[450];
typedef _anon40 type_122[16];
typedef _anon8 type_123[4];
typedef _anon8 type_124[4][2];
typedef _anon8 type_125[11];
typedef short type_126[256];
typedef char type_127[3];
typedef int type_128[64];
typedef _anon17 type_129[450];
typedef unsigned int type_130[16];
typedef char type_132[4];
typedef unsigned int type_133[8];
typedef _anon45 type_134[4];
typedef _anon5 type_135[4];
typedef int type_136[450];
typedef short type_137[3];
typedef short type_138[3][2];
typedef unsigned int type_139[8];
typedef _anon8 type_140[9];
typedef unsigned char type_141[450];
typedef float type_142[128];
typedef _anon8 type_143[9];
typedef char type_144[16];
typedef _anon41 type_145[2];
typedef _anon8 type_146[15];
typedef _anon8 type_147[4];
typedef char type_148[4];
typedef _anon28 type_150[2];
typedef unsigned int type_151[32];
typedef _anon8 type_152[14];
typedef _anon8 type_153[18];
typedef unsigned char type_154[256];
typedef unsigned int type_155[16];
typedef _anon1 type_157[64];
typedef unsigned int type_158[16];
typedef _anon8 type_159[11];
typedef _anon1 type_160[64];
typedef unsigned int type_161[32];
typedef _anon27 type_162[2];
typedef _anon8 type_163[15];
typedef _anon1 type_164[64];
typedef unsigned int type_165[16];
typedef _anon8 type_166[4];
typedef unsigned int type_167[3];
typedef _anon5 type_168[4];
typedef BH_PWORK* type_169[16];
typedef unsigned int type_170[8];
typedef _anon8 type_171[7];
typedef unsigned int type_172[1];
typedef _anon8 type_173[8];
typedef _anon8 type_174[17];
typedef unsigned int type_175[384];
typedef _anon5 type_176[4];
typedef unsigned int type_177[2];
typedef unsigned char type_178[2];
typedef int* type_179[16];
typedef unsigned int type_180[4];
typedef _anon5 type_181[4];
typedef char type_183[32];
typedef npobj* type_184[16];
typedef _anon8 type_185[8];
typedef _anon8 type_186[11];
typedef char type_187[64];
typedef _anon4* type_188[16];
typedef char type_189[4];
typedef _anon8 type_190[11];
typedef _anon17 type_191[16];
typedef short type_192[4];
typedef _anon8 type_193[9];
typedef _anon8 type_194[25];
typedef _anon8 type_195[10];
typedef int type_196[3];
typedef _anon8 type_197[19];
typedef unsigned char type_198[4];
typedef _anon42 type_199[16];
typedef unsigned int type_201[8];
typedef unsigned int type_202[32];
typedef _anon8 type_203[6];
typedef unsigned int type_204[4];
typedef _anon8 type_206[5];
typedef _anon5 type_207[4];
typedef _anon41 type_208[32];
typedef _anon0* type_209[512];
typedef _anon8 type_210[12];
typedef _anon8 type_211[8];
typedef _anon8 type_212[14];
typedef _anon8 type_213[19];
typedef _anon8 type_214[11];
typedef _anon0* type_215[128];
typedef _anon0* type_216[512];
typedef _anon8 type_217[5];
typedef unsigned char type_218[64];
typedef _anon5 type_219[4];
typedef _anon0* type_221[512];
typedef _anon8 type_222[12];

struct _anon0
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	char flr_no;
	char flr_nob;
	unsigned char mdlver;
	unsigned char param;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	int ax;
	int ay;
	int az;
	float ar;
	float aw;
	float ah;
	float ad;
	float car;
	float cah;
	float pxb;
	float pyb;
	float pzb;
	int axb;
	int ayb;
	int azb;
	float gpx;
	float gpy;
	float gpz;
	float lox;
	float loy;
	float loz;
	float aox;
	float aoy;
	float aoz;
	float spd;
	unsigned int flg2;
	unsigned int mdflg;
	unsigned int stflg;
	unsigned int Dummy3;
	int draw_tp;
	int mdl_n;
	void* mskp;
	unsigned int Dummy[1];
	int* skp[16];
	npobj* mbp[16];
	_anon4* txp[16];
	_anon17 mdl[16];
	_anon17* mlwP;
	unsigned int mdl_no;
	int lkono;
	unsigned char* lkwkp;
	unsigned char* exp0;
	unsigned char* exp1;
	unsigned char* exp2;
	unsigned char* exp3;
	unsigned char mtxbuf[64];
	float mtx[16];
	npobj* obj_a;
	npobj* obj_b;
	float shp_ct;
	char clp_jno[8];
	int lok_jno;
	_anon10* mnwP;
	_anon10* mnwPb;
	unsigned int mtn_attr;
	unsigned int mtn_no;
	int frm_no;
	unsigned int frm_mode;
	int hokan_rate;
	unsigned int hokan_count;
	unsigned int hokan_ctbak;
	int mtn_add;
	unsigned int mtn_md;
	unsigned char* mtn_tp;
	int axp;
	int ayp;
	int azp;
	short psh_ct;
	short psh_idx;
	int idx_ct;
	int mtn_chk;
	float ofx;
	float ofy;
	float ofz;
	float sx;
	float sy;
	float sz;
	float sxb;
	float syb;
	float szb;
	float xn;
	float yn;
	float zn;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	unsigned char* objbak;
	_anon53 cspr;
	int pn;
	_anon45* pvp;
	_anon5* tvp;
	_anon45 pv[4];
	_anon5 tv[4];
	int bl_src;
	int bl_dst;
	int ani_ct;
	int tex_id;
	int aspd;
	unsigned int gidx;
	int bank;
	char jno[16];
	char hide[4];
	void(*func)(void*);
	int idx;
	int Dummy2;
};

struct npobj
{
	unsigned int evalflags;
	_anon39* model;
	float pos[3];
	int ang[3];
	float scl[3];
	npobj* child;
	npobj* sibling;
};

struct _anon1
{
	unsigned char flg;
	unsigned char type;
	unsigned char id;
	char flr_no;
	unsigned int attr;
	float px;
	float py;
	float pz;
	float w;
	float h;
	float d;
	unsigned char prm0;
	unsigned char prm1;
	unsigned char prm2;
	unsigned char prm3;
};

struct _anon2
{
	unsigned short flg;
	short ct;
	float scl;
	float px;
	float py;
	float pz;
	float xn;
	float yn;
	float zn;
};

struct _anon3
{
	float x;
	float y;
	float z;
	float u;
	float v;
	unsigned int bcol;
	unsigned int ocol;
};

struct _anon4
{
	_anon30* textures;
	unsigned int nbTexture;
};

struct _anon5
{
	float x;
	float y;
	float z;
	float u;
	float v;
	unsigned int col;
};

struct _anon6
{
	float px;
	float py;
	float pz;
	int ay;
};

struct _anon7
{
	unsigned int ssd_ver;
	unsigned int ssd_flg;
	unsigned int ssd_reserve;
	char keytype;
	char adjust_x;
	char adjust_y;
	char vibration;
	int best_tm[8];
	unsigned int sys_partid;
	unsigned int itm_partid;
	unsigned int fil_partid;
	unsigned int dor_partid;
	unsigned int ss_flg;
	int pdm_no;
	unsigned int typ_flg;
	unsigned short typ_md0;
	unsigned short typ_md1;
	void* typ_exp;
	unsigned int tk_flg;
	unsigned int ts_flg;
	unsigned int gm_flg;
	unsigned int st_flg;
	unsigned int cb_flg;
	unsigned int rm_flg;
	unsigned int pt_flg;
	unsigned int sp_flg;
	unsigned int ef_flg;
	unsigned int error;
	unsigned int version;
	int save_ct;
	char ply_id;
	char stg_no;
	char rom_no;
	char rcase;
	char pos_no;
	char cut_no;
	char flr_no;
	char reserve0;
	int gm_mode;
	unsigned int ev_flg[32];
	unsigned int it_flg[16];
	unsigned int ic_flg[16];
	unsigned int ed_flg[32];
	unsigned int ky_flg[16];
	unsigned int mp_flg[8];
	unsigned int itm[384];
	unsigned int ply_stflg[4];
	_anon41 ply_pos;
	int ply_ang;
	char ply_wno[4];
	short ply_hp[4];
	unsigned char evt_posno[4];
	int time;
	int stv_tm;
	short spray_ct;
	short retry_ct;
	short clear_ct;
	short reserve1;
	unsigned int save_end;
	char stg_nob;
	char rom_nob;
	char pos_nob;
	char rcase_b;
	unsigned int en_flg[4];
	_anon4* et_lp[16][16][100];
	_anon4* ot_lp[1300];
	_anon4* it_lp[200];
	int eft_n;
	_anon4* eft_lp[8];
	int loop_ct;
	int loop_now;
	int cng_pid;
	_anon18* p1per;
	_anon18* p2per;
	_anon18* kbper;
	_anon18* msper;
	_anon18 ms_per;
	int pad_port;
	unsigned int pad_on;
	unsigned int pad_oncpy;
	unsigned int pad_ps;
	unsigned int pad_rs;
	unsigned int pad_old;
	unsigned int pad_onb;
	unsigned int pad_psb;
	unsigned int pad_oldb;
	short pad_ax;
	short pad_ay;
	short pad_dx;
	short pad_dy;
	unsigned short pad_ar;
	unsigned short pad_al;
	int fixcno;
	int fixkno;
	unsigned int exm_attr;
	short evc_no;
	short evc_kn;
	short evc_ono;
	short evc_okn;
	int evc_sc;
	unsigned char mn_mode0;
	unsigned char mn_mode1;
	unsigned char mn_mode2;
	unsigned char mn_mode3;
	unsigned char mn_md0;
	unsigned char mn_md1;
	unsigned char mn_md2;
	unsigned char mn_md3;
	int mn_setct;
	unsigned int mn_stack[8];
	unsigned int sdm_flg;
	unsigned int sdm_mode;
	unsigned char* ltc_bp;
	unsigned int ltc_tsbak;
	int ewk_n;
	unsigned int enow;
	unsigned int onow;
	unsigned int efnow;
	int vsyc_ct;
	int vsyc_flg;
	int fog_ct;
	int bcl_ct;
	int gfrm_ct;
	int gframe;
	int eor_ct;
	unsigned int pfm_cts;
	int evt_tmd;
	int evt_tim;
	int evt_tdg;
	int evt_fcd;
	unsigned int evt_fcdct;
	unsigned int fsize;
	unsigned int rdtsz;
	unsigned char* memp;
	unsigned char* mempb;
	unsigned char* endp;
	unsigned char* rdtp;
	unsigned char* plmdlp;
	unsigned char* lmmdlp;
	unsigned char* wrmdlp;
	unsigned char* wlmdlp;
	unsigned char* plmthp;
	unsigned char* plbmtp;
	unsigned char* plwmtp;
	unsigned char* plzmtp;
	unsigned char* plemtp;
	unsigned char* plexwp;
	unsigned char* plhdwp;
	unsigned char* pletcp;
	unsigned char* subtxp;
	unsigned char* doordp;
	unsigned char* sbs_sp;
	_anon0* obwp;
	_anon0* itwp;
	_anon10* emtp[128];
	_anon10* rmthp;
	unsigned char* mspp;
	unsigned char* lspp;
	unsigned int* mes_ip;
	unsigned int* mes_sp;
	void* mes_tp;
	short txr_n;
	short txr_ct;
	_anon4* txlp[256];
	unsigned char* txdp[256];
	short txloff[256];
	short txb_ct;
	short txb_n;
	short txb[256];
	_anon4* txblp[256];
	_anon15 txbp[256];
	unsigned char* ef_psp;
	_anon30 ef_tex[450];
	_anon4 ef_tlist;
	_anon47 ef;
	short efid[256];
	_anon17 efm[450];
	int ef_ct;
	int ef_ctb;
	int ef_extn;
	int ef_tn[450];
	unsigned char ef_pbkb[450];
	int ef_pbnk;
	int ef_slow;
	int ef_ctrn;
	int yk_ct;
	int mg_ct;
	int bl_ct;
	int windr;
	float winds;
	int windrb;
	float windsb;
	unsigned int thunder;
	float gas_py;
	int en_objn;
	BH_PWORK* en_obj[16];
	int ef_poln;
	int ef_mdfn;
	int ef_linn;
	int ef_ntxn;
	int ef_trsn;
	int ef_pncn;
	int ef_opqn;
	int ef_thln;
	int ef_ntx2dn;
	int ef_trs2dn;
	int ef_pnc2dn;
	int ef_fncn;
	_anon0* ef_pol[512];
	_anon0* ef_mdf[128];
	_anon0* ef_lin[512];
	_anon0* ef_ntx[512];
	_anon0* ef_trs[512];
	_anon0* ef_pnc[512];
	_anon0* ef_opq[512];
	_anon0* ef_thl[512];
	_anon0* ef_ntx2d[128];
	_anon0* ef_trs2d[128];
	_anon0* ef_pnc2d[128];
	_anon0* ef_fnc[512];
	int ob_nlgn;
	int ob_hlgn;
	int ob_spcn;
	_anon0* ob_nlg[32];
	_anon0* ob_hlg[32];
	_anon0* ob_spc[32];
	unsigned int ren_gid;
	_anon26 ren_info;
	_anon30 ren_tex[1];
	_anon4 ren_tlist;
	_anon3 rpb[256];
	int ren_n;
	int ren_idx[4];
	int wt_nbpt;
	float wt_px;
	float wt_pz;
	int wt_xp;
	int wt_zp;
	int wt_minx;
	int wt_minz;
	int wt_maxx;
	int wt_maxz;
	unsigned char* wt_wvp;
	_anon50 mr_pl;
	unsigned char* zan_memp;
	unsigned char* zanp;
	_anon13* lgtp;
	float lg_vx;
	float lg_vy;
	float lg_vz;
	float lg_r;
	float lg_g;
	float lg_b;
	int lg_pnt;
	_anon38 lg_ptb[4];
	int mes_idx;
	unsigned int* mes_dp;
	int mes_ct;
	int mes_tim;
	int mes_fls;
	int mes_sel;
	int mes_seln;
	_anon40 mes_sps[16];
	int rt_sp;
	unsigned char* rt_wp;
	unsigned char* rt_dp;
	unsigned char* rt_nw;
	unsigned char* rt_nx;
	float* rt_ln;
	BH_PWORK* plp;
	_anon1* pl_htp;
	int costume;
	_anon41 hd_pos;
	_anon41 apos;
	_anon1* ahtp;
	int mwal_n;
	int metc_n;
	int mflr_n;
	_anon1 mwalp[64];
	_anon1 metcp[64];
	_anon1 mflrp[64];
	int dla_n;
	_anon1* htp;
	int psh_snd;
	int fog_cngct;
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	float fade_ct;
	float fade_hkn;
	float fade_ao;
	float fade_an;
	float fade_ap;
	float fade_ro;
	float fade_rn;
	float fade_rp;
	float fade_go;
	float fade_gn;
	float fade_gp;
	float fade_bo;
	float fade_bn;
	float fade_bp;
	unsigned int fade_pbk;
	unsigned short ssv_md0;
	unsigned short ssv_md1;
	int ssv_tim;
	float ssv_ct;
	float ssv_hkn;
	float ssv_ao;
	float ssv_an;
	float ssv_ap;
	short fil_no;
	short fil_rt;
	float rvf_sc;
	float rvf_sn;
	unsigned int rvfc[4];
	float cine_an;
	float cine_ap;
	unsigned int sco_flg;
	float amb_r[4];
	float amb_g[4];
	float amb_b[4];
	int sb_id;
	int sb_cmd;
	int sb_rdid;
	int sb_rdsz;
	void* sb_rdp;
	void* sb_mlb;
	void* sb_ppp;
	_anon4* sb_tlist;
	int ddmd;
	_anon21 door;
	int mpmd;
	int mp_prm[4];
	unsigned short gov_md0;
	unsigned short gov_md1;
	int gov_ct;
	void* gov_exp;
	unsigned int com_flg;
	unsigned short com_md0;
	unsigned short com_md1;
	unsigned int com_num;
	void* com_exp;
	short ond_tnm;
	short ond_ud;
	char ond_cx;
	char ond_n[3];
	unsigned char ufo_md;
	unsigned char ufo_flg;
	short ufo_oidx;
	_anon41 ufo_pos;
	unsigned int opt_flg;
	unsigned short opt_md0;
	unsigned short opt_md1;
	void* opt_exp;
	unsigned int etc_idx;
	unsigned int flr_idx;
	int mvi_no;
	int mvi_tp;
	unsigned short mvi_md;
	unsigned short mvi_flg;
	unsigned int mvi_tsb;
	unsigned int mvi_spb;
	unsigned char* mvi_memp;
	unsigned int dcg_tkbak;
	unsigned int dcg_tsbak;
	unsigned int pau_spbak;
	unsigned int pau_pad_on;
	unsigned int pau_pad_ps;
	unsigned int pau_pad_old;
	unsigned char* pdm_dp;
	unsigned char* pdm_pd;
	int pdm_keytpb;
	int gat_ct;
	_anon42 gatc[16];
	int ght_ct;
	unsigned int ghtc[32];
	_anon41 ghtp[32];
	unsigned short db_md0;
	unsigned short db_md1;
	char db_stgno;
	char db_romno;
	char db_rcase;
	char db_muteki;
	short db_px;
	short db_py;
	int db_mes;
	int calc_v;
	unsigned int brkfg;
	char brkfg_typ[32];
	short brkfg_bit[32];
	unsigned int brkfg_tkb;
	unsigned int brkfg_tsb;
	int brkfg_ct;
	unsigned int bmt_size;
	unsigned int lmt_size;
	unsigned int emt_size;
	unsigned int wmt_size;
	char mes[256];
	float sfx;
	float sfy;
	float sfxn;
	float sfyn;
	float sfct;
};

struct _anon8
{
	float u;
	float v;
	float xs;
	float ys;
};

struct _anon9
{
	float px;
	float py;
	float pz;
	short ax;
	short ay;
};

struct _anon10
{
	unsigned int flg;
	unsigned int obj_num;
	unsigned int frm_num;
	void* datP;
	_anon29* md2P;
	unsigned short* atrP;
};

struct _anon11
{
	unsigned short flg;
	unsigned short type;
	short nxt_no;
	short keyf_n;
	_anon55 keyf[16];
};

struct _anon12
{
	_anon16* cutp;
	_anon13* lgtp;
	_anon20* enep;
	_anon20* objp;
	_anon20* itmp;
	_anon24* effp;
	_anon1* walp;
	_anon1* etcp;
	_anon1* flrp;
	_anon6* posp;
	_anon1* rutp;
	unsigned char* ruttp;
	_anon32* evtp;
	_anon11* evcp;
	unsigned int* mesp;
	_anon13* evlp;
	unsigned char* dmp00;
	unsigned char* dmp01;
	unsigned char* dmp02;
	unsigned char* dmp03;
	unsigned char* dmp04;
	unsigned char* dmp05;
	unsigned char* dmp06;
	unsigned char* dmp07;
	unsigned char* dmp08;
	unsigned char* dmp09;
	unsigned char* dmp10;
	unsigned char* dmp11;
	unsigned char* dmp12;
	unsigned char* dmp13;
	unsigned char* dmp14;
	unsigned char* dmp15;
	int cut_n;
	int lgt_n;
	int ene_n;
	int obj_n;
	int itm_n;
	int eff_n;
	int wal_n;
	int etc_n;
	int flr_n;
	int pos_n;
	int rut_n;
	int evc_n;
	int mes_n;
	int evl_n;
	int dmy00;
	int dmy01;
	int dmy02;
	int dmy03;
	int dmy04;
	int dmy05;
	int dmy06;
	int dmy07;
	int dmy08;
	int dmy09;
	int dmy10;
	int dmy11;
	int dmy12;
	int dmy13;
	int dmy14;
	int dmy15;
	int dmy16;
	int dmy17;
	unsigned int flg;
	unsigned int bak_col;
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	float w;
	float h;
	float d;
	float grand[32];
	_anon17 mdl;
	float fog[128];
	char amb_rom;
	char amb_chr;
	char amb_obj;
	char amb_itm;
	float amb_r[4];
	float amb_g[4];
	float amb_b[4];
};

struct BH_PWORK
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	char flr_no;
	char flr_nob;
	unsigned char mdlver;
	unsigned char param;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	int ax;
	int ay;
	int az;
	float ar;
	float aw;
	float ah;
	float ad;
	float car;
	float cah;
	float pxb;
	float pyb;
	float pzb;
	int axb;
	int ayb;
	int azb;
	float gpx;
	float gpy;
	float gpz;
	float lox;
	float loy;
	float loz;
	float aox;
	float aoy;
	float aoz;
	float spd;
	unsigned int flg2;
	unsigned int mdflg;
	unsigned int stflg;
	unsigned int Dummy3;
	int draw_tp;
	int mdl_n;
	void* mskp;
	unsigned int Dummy[1];
	int* skp[16];
	npobj* mbp[16];
	_anon4* txp[16];
	_anon17 mdl[16];
	_anon17* mlwP;
	unsigned int mdl_no;
	int lkono;
	unsigned char* lkwkp;
	unsigned char* exp0;
	unsigned char* exp1;
	unsigned char* exp2;
	unsigned char* exp3;
	unsigned char mtxbuf[64];
	float mtx[16];
	npobj* obj_a;
	npobj* obj_b;
	float shp_ct;
	char clp_jno[8];
	int lok_jno;
	_anon10* mnwP;
	_anon10* mnwPb;
	unsigned int mtn_attr;
	unsigned int mtn_no;
	int frm_no;
	unsigned int frm_mode;
	int hokan_rate;
	unsigned int hokan_count;
	unsigned int hokan_ctbak;
	int mtn_add;
	unsigned int mtn_md;
	unsigned char* mtn_tp;
	int axp;
	int ayp;
	int azp;
	short psh_ct;
	short psh_idx;
	int idx_ct;
	int mtn_chk;
	float ofx;
	float ofy;
	float ofz;
	float sx;
	float sy;
	float sz;
	float sxb;
	float syb;
	float szb;
	float xn;
	float yn;
	float zn;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	int wpnr_no;
	int wpnl_no;
	unsigned int at_flg;
	_anon54 watr;
	_anon31* cpcl;
	short wax;
	short way;
	short waz;
	short waxp;
	short wayp;
	short wazp;
	int hp;
	int dam[64];
	int djnt_no;
	int cpcl_no;
	int dax;
	int day;
	float dpx;
	float dpy;
	float dpz;
	float dvx;
	float dvy;
	float dvz;
	int flr_snd;
	int ko_num;
	int footeff;
	int src_no;
	unsigned char* kdnp;
	int kdnidx;
	void* dan_ap;
	unsigned int comb_flg;
	unsigned int comb_wep;
	int comb_pnt;
	int comb_timeout;
	int total_dam;
	unsigned int Dummy2[2];
};

struct _anon13
{
	unsigned int flg;
	unsigned int type;
	int aspd;
	int lkflg;
	int lkno;
	int lkono;
	int lsrc;
	float px;
	float py;
	float pz;
	float lx;
	float ly;
	float lz;
	float vx;
	float vy;
	float vz;
	float spc;
	float dif;
	float amb;
	float r;
	float g;
	float b;
	float nr;
	float fr;
	int iang;
	int oang;
	int ax;
	int ay;
	int az;
	unsigned int mode;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	float wpx;
	float wpy;
	float wpz;
	float wvx;
	float wvy;
	float wvz;
	float wspc;
	float wdif;
	float wamb;
	float wr;
	float wg;
	float wb;
	float wnr;
	float wfr;
	int wiang;
	int woang;
	int wax;
	int way;
	int waz;
	unsigned char* lkwkp;
	unsigned char* exp;
	_anon35* light;
};

struct _anon14
{
	unsigned int Type;
	unsigned int BitDepth;
	unsigned int PixelFormat;
	unsigned int nWidth;
	unsigned int nHeight;
	unsigned int TextureSize;
	unsigned int fSurfaceFlags;
	unsigned int* pSurface;
	unsigned int* pVirtual;
	unsigned int* pPhysical;
};

struct _anon15
{
	unsigned char* adr;
	unsigned int gidx;
	unsigned int attr;
	unsigned int w;
	unsigned int h;
};

struct _anon16
{
	unsigned char flg;
	unsigned char type;
	char flr_no;
	unsigned char ctab_n;
	_anon19* cuttp;
	float cx;
	float cy;
	float cz;
	float cw;
	float ch;
	float cd;
	_anon28 cam[2];
	unsigned char exd[256];
};

struct _anon17
{
	unsigned int flg;
	unsigned int obj_num;
	void* datP;
	npobj* objP;
	_anon4* texP;
	_anon34* owP;
};

struct _anon18
{
	unsigned int id;
	unsigned int support;
	unsigned int on;
	unsigned int off;
	unsigned int press;
	unsigned int release;
	unsigned short r;
	unsigned short l;
	short x1;
	short y1;
	short x2;
	short y2;
	char* name;
	void* extend;
	unsigned int old;
	_anon51* info;
};

struct _anon19
{
	unsigned int attr;
	char flr_no;
	char reserve0;
	char reserve1;
	char atr_tp;
	float h;
	float dmy;
	float minx;
	float minz;
	float maxx;
	float maxz;
};

struct _anon20
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	char flr_no;
	unsigned char mdlver;
	unsigned char wrk_no;
	char prm1;
	float px;
	float py;
	float pz;
	short ax;
	short az;
	short ay;
	short aspd;
	char hide[4];
};

struct _anon21
{
	unsigned int flg;
	char stg_no;
	char rom_no;
	unsigned char pos_no;
	unsigned char dor_tp;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
};

struct _anon22
{
	unsigned int flg;
	unsigned int atack_ct;
	unsigned int fend_ct;
	unsigned int at_cct;
	short ef_yct;
	short act_ct0;
	short act_ct1;
	short act_ct2;
	float r;
	float l;
	float rn;
	float rmax;
	_anon41 wp_fps1;
	_anon41 wp_fps2;
	_anon41 wp_cps;
	unsigned char ltp;
	unsigned char lr;
	unsigned char lg;
	unsigned char lb;
	unsigned short lnr;
	unsigned short lfr;
	float hrate;
	float ef_scale;
	short snd_wpno;
	short hiteff;
	unsigned short seno0;
	unsigned short seno1;
	char vib_tp;
	char vib_ct;
	char reserve1;
	char reserve2;
};

struct _anon23
{
	short u;
	short v;
};

struct _anon24
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	short flr_no;
	unsigned short mdlver;
	float px;
	float py;
	float pz;
	float sx;
	float sy;
	float sz;
	short ay;
	short ax;
	int lkflg;
	int lkno;
	int lkono;
	float lx;
	float ly;
	float lz;
	int param;
};

struct _anon25
{
	unsigned char b;
	unsigned char g;
	unsigned char r;
	unsigned char a;
};

struct _anon26
{
	void* texaddr;
	_anon14 texsurface;
};

union _anon27
{
	unsigned int color;
	_anon23 tex;
	_anon25 argb;
};

struct _anon28
{
	unsigned short flg;
	unsigned char lgtclip;
	char spd;
	float px;
	float py;
	float pz;
	float ln;
	float w;
	float h;
	float d;
	float y0;
	float y1;
	float y2;
	float y3;
	float am_spd;
	int ax;
	int ay;
	int az;
	int lax;
	int lay;
	short laz0;
	short laz1;
	short laz2;
	short laz3;
	char aa_spd;
	char fil_no;
	char fil_rt;
	char reserve;
	int pers;
	unsigned int hidobj[16];
	unsigned int hidlgt[8];
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
};

struct _anon29
{
	void* p[2];
};

struct _anon30
{
	void* filename;
	unsigned int attr;
	unsigned int texaddr;
};

struct _anon31
{
	short jnt_a;
	short jnt_b;
	int cap_r;
};

struct _anon32
{
	unsigned short* scd0;
	unsigned short* scd1;
	unsigned short* evd;
};

struct _anon33
{
	float a;
	float r;
	float g;
	float b;
};

struct _anon34
{
	unsigned int flg;
	int dmy;
	unsigned int dummy[2];
	float mtx[16];
};

struct _anon35
{
	float mtrx[16];
	_anon41 pnt;
	_anon41 vctr;
	int stat;
	int reserve;
	_anon43 ltcal;
	_anon52 attr;
};

struct _anon36
{
	unsigned short flg;
	short ct;
	float px;
	float py;
	float pz;
};

struct _anon37
{
	unsigned int globalIndex;
	unsigned int bank;
	unsigned int tspparambuffer;
	unsigned int texparambuffer;
	unsigned int texaddr;
	_anon26 texinfo;
	unsigned short count;
	unsigned short dummy;
};

struct _anon38
{
	_anon41 ps;
	float nr;
	float fr;
	float cr;
	float cg;
	float cb;
};

struct _anon39
{
	int* vlist;
	short* plist;
	_anon41 center;
	float r;
};

struct _anon40
{
	float x;
	float y;
};

struct _anon41
{
	float x;
	float y;
	float z;
};

struct _anon42
{
	_anon41 c1;
	_anon41 c2;
	float r1;
	float r2;
};

struct _anon43
{
	float ratten;
	float ipd;
	float nrr;
	float frr;
	float cosi;
	float cose;
	float idev;
	float odev;
	float rate;
	float intns;
	int exp;
	int reserve;
	_anon41 lpnt;
	_anon41 lvctr;
	_anon41 lmvctr;
	_anon33 atten;
	_anon33 amb;
	_anon33 dif;
	_anon33 spc;
	_anon33 mamb;
	_anon33 mdif;
	_anon33 mspc;
};

struct _anon44
{
	float px;
	float py;
	float pz;
	float vx;
	float vy;
	float vz;
	float gx;
	float gy;
	float gz;
	unsigned int at_flg;
	int wpn_no;
	float r;
	float l;
	float rn;
	float rmax;
	int ax;
	int ay;
};

struct _anon45
{
	float x;
	float y;
	float z;
	unsigned int col;
};

struct _anon46
{
	_anon40* p;
	_anon27* col;
	_anon27* tex;
	unsigned int num;
};

struct _anon47
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	short flr_no;
	unsigned short mdlver;
	float px;
	float py;
	float pz;
	float sx;
	float sy;
	float sz;
	short ay;
	short ax;
};

struct _anon48
{
	_anon41* p;
	_anon27* col;
	_anon27* tex;
	unsigned int num;
};

struct _anon49
{
	unsigned int flg;
	int camver;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	float vx;
	float vy;
	float vz;
	float wpx;
	float wpy;
	float wpz;
	float plx;
	float ply;
	float plz;
	float pxp;
	float pyp;
	float pzp;
	float ofx;
	float ofy;
	float ofz;
	int ax;
	int ay;
	int az;
	int axp;
	int ayp;
	int azp;
	float ln;
	float pln;
	float xr;
	float xn;
	float yr;
	float yn;
	int pers;
	int ppers;
	int ncut;
	int ocut;
	unsigned int ocflg;
	unsigned int attr;
	float mtx[16];
	float mtxb[16];
	int evc_no;
	int hct;
	int ct0;
	int ct1;
	int keyf_no;
	float frm;
	float spd;
	float pxn;
	float pyn;
	float pzn;
	int axn;
	int ayn;
	int azn;
	int pe_ax;
	int pe_pers;
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	float ips[3][20];
	float ian[3][20];
	float ipf[3][20];
	float icr[3][20];
};

struct _anon50
{
	float px;
	float py;
	float pz;
	float vx;
	float vy;
	float vz;
};

struct _anon51
{
	unsigned int type;
	unsigned int reserved[3];
	unsigned char is_root;
	unsigned char area_code;
	unsigned char connector_dir[2];
	char product_name[32];
	char license[64];
	unsigned short stdby_pow;
	unsigned short max_pow;
};

struct _anon52
{
	int lsrc;
	float iamb;
	float idif;
	float ispc;
	float nrang;
	float frang;
	void* func;
	int iang;
	int oang;
	_anon33 argb;
};

struct _anon53
{
	_anon41 c;
	float r;
};

struct _anon54
{
	_anon41 c1;
	_anon41 c2;
	float r;
};

struct _anon55
{
	unsigned short flg;
	short frame;
	float px;
	float py;
	float pz;
	short ax;
	short ay;
	short az;
	short pers;
	unsigned int hidobj[8];
	unsigned int hidlgt[4];
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	short lkflg;
	short lkno;
	short lkono;
	short nxt_no;
	float lx;
	float ly;
	float lz;
	float prm_0;
	float prm_1;
	float prm_2;
	float prm_3;
	float prm_4;
	unsigned char* recp;
};

struct _anon56
{
	float px;
	float py;
	float pz;
	float ox;
	float oy;
	float oz;
};*/

void bhEffDmy(O_WRK* op);
void bhEffFil(O_WRK* op);
void bhEffBG(O_WRK* op);
void bhEff2D(O_WRK* op);
void bhEff000(O_WRK* op);
void bhEff001(O_WRK* op);
void bhEff002(O_WRK* op);
void bhDrawWeaponEffect(O_WRK* op);
void bhEff003(O_WRK* op);
void bhEff004();
void bhEff005(O_WRK* op);
void bhEff006(O_WRK* op);
void bhEff007(O_WRK* op);
void bhEff008(O_WRK* op);
void bhEff009(O_WRK* op);
void bhEff010(O_WRK* op);
void bhEff011(O_WRK* op);
void bhEff012(O_WRK* op);
void bhEff013(O_WRK* op);
void bhEff014(O_WRK* op);
void bhEff015(O_WRK* op);
void bhEff016(O_WRK* op);
void bhEff017(O_WRK* op);
void bhEff018(O_WRK* op);
void bhEff019(O_WRK* op);
void bhDraw021();
void bhEff021(O_WRK* op);
void bhDraw022(O_WRK* op);
void bhEff022(O_WRK* op);
void bhEff023(O_WRK* op);
void bhDraw024(O_WRK* op);
void bhEff024(O_WRK* op);
void bhDraw025(O_WRK* op);
void bhEff025(O_WRK* op);
void bhEff026(O_WRK* op);
void bhDraw027(O_WRK* op);
void bhEff027(O_WRK* op);
void bhEff028();
void bhEff029(O_WRK* op);
void bhEff100(O_WRK* op);
void bhEff101(O_WRK* op);
void bhEff102(O_WRK* op);
void bhEff103(O_WRK* op);
void bhEff104(O_WRK* op);
void bhEff105(O_WRK* op);
void bhEff106(O_WRK* op);
void bhDraw107(O_WRK* op);
void bhEff107(O_WRK* op);
void bhEff108(O_WRK* op);
void bhEff109(O_WRK* op);
void bhEff110(O_WRK* op);
void bhEff111(O_WRK* op);
void bhEff112(O_WRK* op);
void bhEff113(O_WRK* op);
void bhDraw114(O_WRK* op);
void bhEff114(O_WRK* op);
void bhEff115(O_WRK* op);
void bhEff116(O_WRK* op);
void bhEff117(O_WRK* op);
void bhEff118(O_WRK* op);
void bhEff119(O_WRK* op);
void bhEff120(O_WRK* op);
void bhEff121(O_WRK* op);
void bhEff122(O_WRK* op);
void bhEff123(O_WRK* op);
void bhEff124(O_WRK* op);
void bhEff125(O_WRK* op);
void bhEff126(O_WRK* op);
void bhEff127(O_WRK* op);
void bhEff128(O_WRK* op);
void bhEff129();
void bhEff130(O_WRK* op);
void bhEff131(O_WRK* op);
void bhEff132(O_WRK* op);

#endif
