#ifndef _EFFSUB4_H_
#define _EFFSUB4_H_

#include "types.h"

/*typedef struct _anon0;
typedef struct npobj;
typedef struct _anon1;
typedef struct _anon2;
typedef struct _anon3;
typedef struct _anon4;
typedef struct _anon5;
typedef struct _anon6;
typedef struct _anon7;
typedef struct _anon8;
typedef struct _anon9;
typedef struct _anon10;
typedef struct _anon11;
typedef struct _anon12;
typedef struct _anon13;
typedef struct _anon14;
typedef struct _anon15;
typedef struct _anon16;
typedef struct BH_PWORK;
typedef struct _anon17;
typedef struct _anon18;
typedef struct _anon19;
typedef struct _anon20;
typedef struct _anon21;
typedef struct _anon22;
typedef struct _anon23;
typedef struct _anon24;
typedef struct _anon25;
typedef struct _anon26;
typedef struct _anon27;
typedef struct _anon28;
typedef struct _anon29;
typedef struct _anon30;
typedef struct _anon31;
typedef struct _anon32;
typedef struct _anon33;
typedef struct _anon34;
typedef struct _anon35;
typedef struct _anon36;
typedef struct _anon37;
typedef struct _anon38;
typedef struct _anon39;
typedef struct _anon40;
typedef struct _anon41;

typedef void(*type_43)(_anon1*);
typedef void(*type_56)(_anon1*);
typedef void(*type_67)(_anon1*);
typedef void(*type_80)(_anon1*);
typedef void(*type_121)(void*);

typedef float type_0[16];
typedef unsigned int type_1[4];
typedef _anon1* type_2[512];
typedef _anon31* type_3[11];
typedef _anon1* type_4[32];
typedef _anon3* type_5[16];
typedef _anon4* type_6[5];
typedef _anon1* type_7[32];
typedef _anon1* type_8[512];
typedef _anon3* type_9[16][16];
typedef _anon3* type_10[16][16][100];
typedef char type_11[8];
typedef _anon4* type_12[2];
typedef _anon1* type_13[32];
typedef _anon1* type_14[512];
typedef _anon31 type_15[1];
typedef _anon3* type_16[1300];
typedef char type_17[32];
typedef _anon1* type_18[512];
typedef _anon3* type_19[200];
typedef short type_20[32];
typedef _anon20 type_21[1];
typedef float type_22[2];
typedef _anon1* type_23[128];
typedef unsigned int type_24[1];
typedef float type_25[40];
typedef _anon10 type_26[256];
typedef _anon3* type_27[8];
typedef int* type_28[16];
typedef _anon1* type_29[128];
typedef _anon0 type_30[40];
typedef _anon31 type_31[13];
typedef npobj* type_32[16];
typedef _anon31 type_33[29];
typedef _anon1* type_34[128];
typedef _anon0 type_35[40];
typedef _anon31 type_36[10];
typedef int type_37[4];
typedef _anon3* type_38[16];
typedef unsigned int type_39[4];
typedef _anon14 type_40[16];
typedef _anon23 type_41[11];
typedef _anon1* type_42[512];
typedef float type_44[16];
typedef char type_45[256];
typedef float type_46[2];
typedef _anon0 type_47[16];
typedef float type_48[4];
typedef _anon0 type_49[16];
typedef float type_50[4];
typedef _anon0 type_51[16];
typedef float type_52[4];
typedef float type_53[3];
typedef _anon8* type_54[128];
typedef float type_55[3][1];
typedef float type_57[3];
typedef unsigned char type_58[64];
typedef float type_59[3][20];
typedef unsigned int type_60[4];
typedef _anon1 type_61[0];
typedef float type_62[3];
typedef float type_63[32];
typedef float type_64[3][20];
typedef _anon31 type_65[32];
typedef float type_66[32];
typedef float type_68[3];
typedef _anon31 type_69[15];
typedef float type_70[3][20];
typedef float type_71[32];
typedef _anon4* type_72[1];
typedef char type_73[8];
typedef int type_74[32];
typedef float type_75[3];
typedef float type_76[3][20];
typedef _anon4* type_77[1];
typedef int type_78[32];
typedef _anon0 type_79[32];
typedef void* type_81[2];
typedef _anon31 type_82[1];
typedef _anon3* type_83[256];
typedef int type_84[4];
typedef unsigned char* type_85[256];
typedef unsigned int type_86[2];
typedef short type_87[256];
typedef _anon31 type_88[13];
typedef _anon26 type_89[4];
typedef float type_90[3];
typedef short type_91[256];
typedef int type_92[3];
typedef int type_93[8];
typedef float type_94[3];
typedef _anon3* type_95[256];
typedef _anon31 type_96[12];
typedef _anon13 type_97[256];
typedef _anon20 type_98[450];
typedef _anon4* type_99[2];
typedef _anon28 type_100[16];
typedef _anon4* type_101[4];
typedef _anon31 type_102[14];
typedef _anon31 type_103[11];
typedef short type_104[256];
typedef char type_105[3];
typedef int type_106[64];
typedef _anon14 type_107[450];
typedef _anon4* type_108[1];
typedef _anon31 type_109[48];
typedef _anon4* type_110[11];
typedef _anon32 type_111[4];
typedef _anon5 type_112[4];
typedef _anon4 type_113[15];
typedef int type_114[450];
typedef unsigned int type_115[8];
typedef unsigned char type_116[450];
typedef _anon4* type_117[4];
typedef unsigned int type_118[2];
typedef char type_119[16];
typedef char type_120[4];
typedef unsigned int type_122[32];
typedef unsigned int type_123[16];
typedef _anon34 type_124[64];
typedef unsigned int type_125[16];
typedef _anon34 type_126[64];
typedef unsigned int type_127[32];
typedef _anon34 type_128[64];
typedef _anon4* type_129[2];
typedef unsigned int type_130[16];
typedef unsigned int type_131[3];
typedef BH_PWORK* type_132[16];
typedef unsigned int type_133[8];
typedef unsigned int type_134[1];
typedef unsigned int type_135[384];
typedef unsigned int type_136[2];
typedef unsigned char type_137[2];
typedef unsigned int type_138[4];
typedef int* type_139[16];
typedef char type_140[32];
typedef npobj* type_141[16];
typedef float type_142[2];
typedef float type_143[2][11];
typedef char type_144[64];
typedef _anon3* type_145[16];
typedef char type_146[4];
typedef _anon32 type_147[3];
typedef _anon14 type_148[16];
typedef short type_149[4];
typedef _anon31* type_150[2];
typedef unsigned char type_151[4];
typedef _anon29 type_152[16];
typedef char type_153[192];
typedef unsigned int type_154[32];
typedef _anon31* type_155[2];
typedef _anon0 type_156[32];
typedef _anon1* type_157[512];
typedef _anon1* type_158[128];
typedef float type_159[2];
typedef _anon1* type_160[512];
typedef unsigned char type_161[64];
typedef _anon1* type_162[512];
typedef _anon4* type_163[2];

struct _anon0
{
	float x;
	float y;
	float z;
};

struct npobj
{
	unsigned int evalflags;
	_anon27* model;
	float pos[3];
	int ang[3];
	float scl[3];
	npobj* child;
	npobj* sibling;
};

struct _anon1
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	char flr_no;
	char flr_nob;
	unsigned char mdlver;
	unsigned char param;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	int ax;
	int ay;
	int az;
	float ar;
	float aw;
	float ah;
	float ad;
	float car;
	float cah;
	float pxb;
	float pyb;
	float pzb;
	int axb;
	int ayb;
	int azb;
	float gpx;
	float gpy;
	float gpz;
	float lox;
	float loy;
	float loz;
	float aox;
	float aoy;
	float aoz;
	float spd;
	unsigned int flg2;
	unsigned int mdflg;
	unsigned int stflg;
	unsigned int Dummy3;
	int draw_tp;
	int mdl_n;
	void* mskp;
	unsigned int Dummy[1];
	int* skp[16];
	npobj* mbp[16];
	_anon3* txp[16];
	_anon14 mdl[16];
	_anon14* mlwP;
	unsigned int mdl_no;
	int lkono;
	unsigned char* lkwkp;
	unsigned char* exp0;
	unsigned char* exp1;
	unsigned char* exp2;
	unsigned char* exp3;
	unsigned char mtxbuf[64];
	float mtx[16];
	npobj* obj_a;
	npobj* obj_b;
	float shp_ct;
	char clp_jno[8];
	int lok_jno;
	_anon8* mnwP;
	_anon8* mnwPb;
	unsigned int mtn_attr;
	unsigned int mtn_no;
	int frm_no;
	unsigned int frm_mode;
	int hokan_rate;
	unsigned int hokan_count;
	unsigned int hokan_ctbak;
	int mtn_add;
	unsigned int mtn_md;
	unsigned char* mtn_tp;
	int axp;
	int ayp;
	int azp;
	short psh_ct;
	short psh_idx;
	int idx_ct;
	int mtn_chk;
	float ofx;
	float ofy;
	float ofz;
	float sx;
	float sy;
	float sz;
	float sxb;
	float syb;
	float szb;
	float xn;
	float yn;
	float zn;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	unsigned char* objbak;
	_anon39 cspr;
	int pn;
	_anon32* pvp;
	_anon5* tvp;
	_anon32 pv[4];
	_anon5 tv[4];
	int bl_src;
	int bl_dst;
	int ani_ct;
	int tex_id;
	int aspd;
	unsigned int gidx;
	int bank;
	char jno[16];
	char hide[4];
	void(*func)(void*);
	int idx;
	int Dummy2;
};

struct _anon2
{
	unsigned int flg;
	unsigned int num;
	unsigned char* exp0;
	unsigned char* exp1;
	unsigned char* exp2;
};

struct _anon3
{
	_anon20* textures;
	unsigned int nbTexture;
};

struct _anon4
{
	short ptrn;
	short timer;
};

struct _anon5
{
	float x;
	float y;
	float z;
	float u;
	float v;
	unsigned int col;
};

struct _anon6
{
	_anon2 dtbl;
	float size[40];
	_anon0 vtx_pos[40];
	_anon0 add_vec[40];
};

struct _anon7
{
	unsigned int ssd_ver;
	unsigned int ssd_flg;
	unsigned int ssd_reserve;
	char keytype;
	char adjust_x;
	char adjust_y;
	char vibration;
	int best_tm[8];
	unsigned int sys_partid;
	unsigned int itm_partid;
	unsigned int fil_partid;
	unsigned int dor_partid;
	unsigned int ss_flg;
	int pdm_no;
	unsigned int typ_flg;
	unsigned short typ_md0;
	unsigned short typ_md1;
	void* typ_exp;
	unsigned int tk_flg;
	unsigned int ts_flg;
	unsigned int gm_flg;
	unsigned int st_flg;
	unsigned int cb_flg;
	unsigned int rm_flg;
	unsigned int pt_flg;
	unsigned int sp_flg;
	unsigned int ef_flg;
	unsigned int error;
	unsigned int version;
	int save_ct;
	char ply_id;
	char stg_no;
	char rom_no;
	char rcase;
	char pos_no;
	char cut_no;
	char flr_no;
	char reserve0;
	int gm_mode;
	unsigned int ev_flg[32];
	unsigned int it_flg[16];
	unsigned int ic_flg[16];
	unsigned int ed_flg[32];
	unsigned int ky_flg[16];
	unsigned int mp_flg[8];
	unsigned int itm[384];
	unsigned int ply_stflg[4];
	_anon0 ply_pos;
	int ply_ang;
	char ply_wno[4];
	short ply_hp[4];
	unsigned char evt_posno[4];
	int time;
	int stv_tm;
	short spray_ct;
	short retry_ct;
	short clear_ct;
	short reserve1;
	unsigned int save_end;
	char stg_nob;
	char rom_nob;
	char pos_nob;
	char rcase_b;
	unsigned int en_flg[4];
	_anon3* et_lp[16][16][100];
	_anon3* ot_lp[1300];
	_anon3* it_lp[200];
	int eft_n;
	_anon3* eft_lp[8];
	int loop_ct;
	int loop_now;
	int cng_pid;
	_anon15* p1per;
	_anon15* p2per;
	_anon15* kbper;
	_anon15* msper;
	_anon15 ms_per;
	int pad_port;
	unsigned int pad_on;
	unsigned int pad_oncpy;
	unsigned int pad_ps;
	unsigned int pad_rs;
	unsigned int pad_old;
	unsigned int pad_onb;
	unsigned int pad_psb;
	unsigned int pad_oldb;
	short pad_ax;
	short pad_ay;
	short pad_dx;
	short pad_dy;
	unsigned short pad_ar;
	unsigned short pad_al;
	int fixcno;
	int fixkno;
	unsigned int exm_attr;
	short evc_no;
	short evc_kn;
	short evc_ono;
	short evc_okn;
	int evc_sc;
	unsigned char mn_mode0;
	unsigned char mn_mode1;
	unsigned char mn_mode2;
	unsigned char mn_mode3;
	unsigned char mn_md0;
	unsigned char mn_md1;
	unsigned char mn_md2;
	unsigned char mn_md3;
	int mn_setct;
	unsigned int mn_stack[8];
	unsigned int sdm_flg;
	unsigned int sdm_mode;
	unsigned char* ltc_bp;
	unsigned int ltc_tsbak;
	int ewk_n;
	unsigned int enow;
	unsigned int onow;
	unsigned int efnow;
	int vsyc_ct;
	int vsyc_flg;
	int fog_ct;
	int bcl_ct;
	int gfrm_ct;
	int gframe;
	int eor_ct;
	unsigned int pfm_cts;
	int evt_tmd;
	int evt_tim;
	int evt_tdg;
	int evt_fcd;
	unsigned int evt_fcdct;
	unsigned int fsize;
	unsigned int rdtsz;
	unsigned char* memp;
	unsigned char* mempb;
	unsigned char* endp;
	unsigned char* rdtp;
	unsigned char* plmdlp;
	unsigned char* lmmdlp;
	unsigned char* wrmdlp;
	unsigned char* wlmdlp;
	unsigned char* plmthp;
	unsigned char* plbmtp;
	unsigned char* plwmtp;
	unsigned char* plzmtp;
	unsigned char* plemtp;
	unsigned char* plexwp;
	unsigned char* plhdwp;
	unsigned char* pletcp;
	unsigned char* subtxp;
	unsigned char* doordp;
	unsigned char* sbs_sp;
	_anon1* obwp;
	_anon1* itwp;
	_anon8* emtp[128];
	_anon8* rmthp;
	unsigned char* mspp;
	unsigned char* lspp;
	unsigned int* mes_ip;
	unsigned int* mes_sp;
	void* mes_tp;
	short txr_n;
	short txr_ct;
	_anon3* txlp[256];
	unsigned char* txdp[256];
	short txloff[256];
	short txb_ct;
	short txb_n;
	short txb[256];
	_anon3* txblp[256];
	_anon13 txbp[256];
	unsigned char* ef_psp;
	_anon20 ef_tex[450];
	_anon3 ef_tlist;
	_anon33 ef;
	short efid[256];
	_anon14 efm[450];
	int ef_ct;
	int ef_ctb;
	int ef_extn;
	int ef_tn[450];
	unsigned char ef_pbkb[450];
	int ef_pbnk;
	int ef_slow;
	int ef_ctrn;
	int yk_ct;
	int mg_ct;
	int bl_ct;
	int windr;
	float winds;
	int windrb;
	float windsb;
	unsigned int thunder;
	float gas_py;
	int en_objn;
	BH_PWORK* en_obj[16];
	int ef_poln;
	int ef_mdfn;
	int ef_linn;
	int ef_ntxn;
	int ef_trsn;
	int ef_pncn;
	int ef_opqn;
	int ef_thln;
	int ef_ntx2dn;
	int ef_trs2dn;
	int ef_pnc2dn;
	int ef_fncn;
	_anon1* ef_pol[512];
	_anon1* ef_mdf[128];
	_anon1* ef_lin[512];
	_anon1* ef_ntx[512];
	_anon1* ef_trs[512];
	_anon1* ef_pnc[512];
	_anon1* ef_opq[512];
	_anon1* ef_thl[512];
	_anon1* ef_ntx2d[128];
	_anon1* ef_trs2d[128];
	_anon1* ef_pnc2d[128];
	_anon1* ef_fnc[512];
	int ob_nlgn;
	int ob_hlgn;
	int ob_spcn;
	_anon1* ob_nlg[32];
	_anon1* ob_hlg[32];
	_anon1* ob_spc[32];
	unsigned int ren_gid;
	_anon18 ren_info;
	_anon20 ren_tex[1];
	_anon3 ren_tlist;
	_anon10 rpb[256];
	int ren_n;
	int ren_idx[4];
	int wt_nbpt;
	float wt_px;
	float wt_pz;
	int wt_xp;
	int wt_zp;
	int wt_minx;
	int wt_minz;
	int wt_maxx;
	int wt_maxz;
	unsigned char* wt_wvp;
	_anon36 mr_pl;
	unsigned char* zan_memp;
	unsigned char* zanp;
	_anon22* lgtp;
	float lg_vx;
	float lg_vy;
	float lg_vz;
	float lg_r;
	float lg_g;
	float lg_b;
	int lg_pnt;
	_anon26 lg_ptb[4];
	int mes_idx;
	unsigned int* mes_dp;
	int mes_ct;
	int mes_tim;
	int mes_fls;
	int mes_sel;
	int mes_seln;
	_anon28 mes_sps[16];
	int rt_sp;
	unsigned char* rt_wp;
	unsigned char* rt_dp;
	unsigned char* rt_nw;
	unsigned char* rt_nx;
	float* rt_ln;
	BH_PWORK* plp;
	_anon34* pl_htp;
	int costume;
	_anon0 hd_pos;
	_anon0 apos;
	_anon34* ahtp;
	int mwal_n;
	int metc_n;
	int mflr_n;
	_anon34 mwalp[64];
	_anon34 metcp[64];
	_anon34 mflrp[64];
	int dla_n;
	_anon34* htp;
	int psh_snd;
	int fog_cngct;
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	float fade_ct;
	float fade_hkn;
	float fade_ao;
	float fade_an;
	float fade_ap;
	float fade_ro;
	float fade_rn;
	float fade_rp;
	float fade_go;
	float fade_gn;
	float fade_gp;
	float fade_bo;
	float fade_bn;
	float fade_bp;
	unsigned int fade_pbk;
	unsigned short ssv_md0;
	unsigned short ssv_md1;
	int ssv_tim;
	float ssv_ct;
	float ssv_hkn;
	float ssv_ao;
	float ssv_an;
	float ssv_ap;
	short fil_no;
	short fil_rt;
	float rvf_sc;
	float rvf_sn;
	unsigned int rvfc[4];
	float cine_an;
	float cine_ap;
	unsigned int sco_flg;
	float amb_r[4];
	float amb_g[4];
	float amb_b[4];
	int sb_id;
	int sb_cmd;
	int sb_rdid;
	int sb_rdsz;
	void* sb_rdp;
	void* sb_mlb;
	void* sb_ppp;
	_anon3* sb_tlist;
	int ddmd;
	_anon16 door;
	int mpmd;
	int mp_prm[4];
	unsigned short gov_md0;
	unsigned short gov_md1;
	int gov_ct;
	void* gov_exp;
	unsigned int com_flg;
	unsigned short com_md0;
	unsigned short com_md1;
	unsigned int com_num;
	void* com_exp;
	short ond_tnm;
	short ond_ud;
	char ond_cx;
	char ond_n[3];
	unsigned char ufo_md;
	unsigned char ufo_flg;
	short ufo_oidx;
	_anon0 ufo_pos;
	unsigned int opt_flg;
	unsigned short opt_md0;
	unsigned short opt_md1;
	void* opt_exp;
	unsigned int etc_idx;
	unsigned int flr_idx;
	int mvi_no;
	int mvi_tp;
	unsigned short mvi_md;
	unsigned short mvi_flg;
	unsigned int mvi_tsb;
	unsigned int mvi_spb;
	unsigned char* mvi_memp;
	unsigned int dcg_tkbak;
	unsigned int dcg_tsbak;
	unsigned int pau_spbak;
	unsigned int pau_pad_on;
	unsigned int pau_pad_ps;
	unsigned int pau_pad_old;
	unsigned char* pdm_dp;
	unsigned char* pdm_pd;
	int pdm_keytpb;
	int gat_ct;
	_anon29 gatc[16];
	int ght_ct;
	unsigned int ghtc[32];
	_anon0 ghtp[32];
	unsigned short db_md0;
	unsigned short db_md1;
	char db_stgno;
	char db_romno;
	char db_rcase;
	char db_muteki;
	short db_px;
	short db_py;
	int db_mes;
	int calc_v;
	unsigned int brkfg;
	char brkfg_typ[32];
	short brkfg_bit[32];
	unsigned int brkfg_tkb;
	unsigned int brkfg_tsb;
	int brkfg_ct;
	unsigned int bmt_size;
	unsigned int lmt_size;
	unsigned int emt_size;
	unsigned int wmt_size;
	char mes[256];
	float sfx;
	float sfy;
	float sfxn;
	float sfyn;
	float sfct;
};

struct _anon8
{
	unsigned int flg;
	unsigned int obj_num;
	unsigned int frm_num;
	void* datP;
	_anon19* md2P;
	unsigned short* atrP;
};

struct _anon9
{
	_anon2 dtbl;
	float g[16];
	_anon0 add_vec[16];
	_anon0 vtx_pos[16];
	_anon0 vtx_pos2[16];
};

struct _anon10
{
	float x;
	float y;
	float z;
	float u;
	float v;
	unsigned int bcol;
	unsigned int ocol;
};

struct _anon11
{
	unsigned int flg;
	int dmy;
	unsigned int dummy[2];
	float mtx[16];
};

struct _anon12
{
	unsigned int Type;
	unsigned int BitDepth;
	unsigned int PixelFormat;
	unsigned int nWidth;
	unsigned int nHeight;
	unsigned int TextureSize;
	unsigned int fSurfaceFlags;
	unsigned int* pSurface;
	unsigned int* pVirtual;
	unsigned int* pPhysical;
};

struct _anon13
{
	unsigned char* adr;
	unsigned int gidx;
	unsigned int attr;
	unsigned int w;
	unsigned int h;
};

struct _anon14
{
	unsigned int flg;
	unsigned int obj_num;
	void* datP;
	npobj* objP;
	_anon3* texP;
	_anon11* owP;
};

struct _anon15
{
	unsigned int id;
	unsigned int support;
	unsigned int on;
	unsigned int off;
	unsigned int press;
	unsigned int release;
	unsigned short r;
	unsigned short l;
	short x1;
	short y1;
	short x2;
	short y2;
	char* name;
	void* extend;
	unsigned int old;
	_anon37* info;
};

struct _anon16
{
	unsigned int flg;
	char stg_no;
	char rom_no;
	unsigned char pos_no;
	unsigned char dor_tp;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
};

struct BH_PWORK
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	char flr_no;
	char flr_nob;
	unsigned char mdlver;
	unsigned char param;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	int ax;
	int ay;
	int az;
	float ar;
	float aw;
	float ah;
	float ad;
	float car;
	float cah;
	float pxb;
	float pyb;
	float pzb;
	int axb;
	int ayb;
	int azb;
	float gpx;
	float gpy;
	float gpz;
	float lox;
	float loy;
	float loz;
	float aox;
	float aoy;
	float aoz;
	float spd;
	unsigned int flg2;
	unsigned int mdflg;
	unsigned int stflg;
	unsigned int Dummy3;
	int draw_tp;
	int mdl_n;
	void* mskp;
	unsigned int Dummy[1];
	int* skp[16];
	npobj* mbp[16];
	_anon3* txp[16];
	_anon14 mdl[16];
	_anon14* mlwP;
	unsigned int mdl_no;
	int lkono;
	unsigned char* lkwkp;
	unsigned char* exp0;
	unsigned char* exp1;
	unsigned char* exp2;
	unsigned char* exp3;
	unsigned char mtxbuf[64];
	float mtx[16];
	npobj* obj_a;
	npobj* obj_b;
	float shp_ct;
	char clp_jno[8];
	int lok_jno;
	_anon8* mnwP;
	_anon8* mnwPb;
	unsigned int mtn_attr;
	unsigned int mtn_no;
	int frm_no;
	unsigned int frm_mode;
	int hokan_rate;
	unsigned int hokan_count;
	unsigned int hokan_ctbak;
	int mtn_add;
	unsigned int mtn_md;
	unsigned char* mtn_tp;
	int axp;
	int ayp;
	int azp;
	short psh_ct;
	short psh_idx;
	int idx_ct;
	int mtn_chk;
	float ofx;
	float ofy;
	float ofz;
	float sx;
	float sy;
	float sz;
	float sxb;
	float syb;
	float szb;
	float xn;
	float yn;
	float zn;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	int wpnr_no;
	int wpnl_no;
	unsigned int at_flg;
	_anon40 watr;
	_anon21* cpcl;
	short wax;
	short way;
	short waz;
	short waxp;
	short wayp;
	short wazp;
	int hp;
	int dam[64];
	int djnt_no;
	int cpcl_no;
	int dax;
	int day;
	float dpx;
	float dpy;
	float dpz;
	float dvx;
	float dvy;
	float dvz;
	int flr_snd;
	int ko_num;
	int footeff;
	int src_no;
	unsigned char* kdnp;
	int kdnidx;
	void* dan_ap;
	unsigned int comb_flg;
	unsigned int comb_wep;
	int comb_pnt;
	int comb_timeout;
	int total_dam;
	unsigned int Dummy2[2];
};

struct _anon17
{
	_anon2 dtbl;
	float size[32];
	float g[32];
	float r[32];
	int rot[32];
	int rot_spd[32];
	_anon0 vtx_pos[32];
};

struct _anon18
{
	void* texaddr;
	_anon12 texsurface;
};

struct _anon19
{
	void* p[2];
};

struct _anon20
{
	void* filename;
	unsigned int attr;
	unsigned int texaddr;
};

struct _anon21
{
	short jnt_a;
	short jnt_b;
	int cap_r;
};

struct _anon22
{
	unsigned int flg;
	unsigned int type;
	int aspd;
	int lkflg;
	int lkno;
	int lkono;
	int lsrc;
	float px;
	float py;
	float pz;
	float lx;
	float ly;
	float lz;
	float vx;
	float vy;
	float vz;
	float spc;
	float dif;
	float amb;
	float r;
	float g;
	float b;
	float nr;
	float fr;
	int iang;
	int oang;
	int ax;
	int ay;
	int az;
	unsigned int mode;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	float wpx;
	float wpy;
	float wpz;
	float wvx;
	float wvy;
	float wvz;
	float wspc;
	float wdif;
	float wamb;
	float wr;
	float wg;
	float wb;
	float wnr;
	float wfr;
	int wiang;
	int woang;
	int wax;
	int way;
	int waz;
	unsigned char* lkwkp;
	unsigned char* exp;
	_anon25* light;
};

struct _anon23
{
	float spd;
	float e;
	float g;
	short id;
	short col;
	short wcnt;
	short lmode;
};

struct _anon24
{
	float a;
	float r;
	float g;
	float b;
};

struct _anon25
{
	float mtrx[16];
	_anon0 pnt;
	_anon0 vctr;
	int stat;
	int reserve;
	_anon30 ltcal;
	_anon38 attr;
};

struct _anon26
{
	_anon0 ps;
	float nr;
	float fr;
	float cr;
	float cg;
	float cb;
};

struct _anon27
{
	int* vlist;
	short* plist;
	_anon0 center;
	float r;
};

struct _anon28
{
	float x;
	float y;
};

struct _anon29
{
	_anon0 c1;
	_anon0 c2;
	float r1;
	float r2;
};

struct _anon30
{
	float ratten;
	float ipd;
	float nrr;
	float frr;
	float cosi;
	float cose;
	float idev;
	float odev;
	float rate;
	float intns;
	int exp;
	int reserve;
	_anon0 lpnt;
	_anon0 lvctr;
	_anon0 lmvctr;
	_anon24 atten;
	_anon24 amb;
	_anon24 dif;
	_anon24 spc;
	_anon24 mamb;
	_anon24 mdif;
	_anon24 mspc;
};

struct _anon31
{
	float u;
	float v;
	float xs;
	float ys;
};

struct _anon32
{
	float x;
	float y;
	float z;
	unsigned int col;
};

struct _anon33
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	short flr_no;
	unsigned short mdlver;
	float px;
	float py;
	float pz;
	float sx;
	float sy;
	float sz;
	short ay;
	short ax;
};

struct _anon34
{
	unsigned char flg;
	unsigned char type;
	unsigned char id;
	char flr_no;
	unsigned int attr;
	float px;
	float py;
	float pz;
	float w;
	float h;
	float d;
	unsigned char prm0;
	unsigned char prm1;
	unsigned char prm2;
	unsigned char prm3;
};

struct _anon35
{
	unsigned int flg;
	int camver;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	float vx;
	float vy;
	float vz;
	float wpx;
	float wpy;
	float wpz;
	float plx;
	float ply;
	float plz;
	float pxp;
	float pyp;
	float pzp;
	float ofx;
	float ofy;
	float ofz;
	int ax;
	int ay;
	int az;
	int axp;
	int ayp;
	int azp;
	float ln;
	float pln;
	float xr;
	float xn;
	float yr;
	float yn;
	int pers;
	int ppers;
	int ncut;
	int ocut;
	unsigned int ocflg;
	unsigned int attr;
	float mtx[16];
	float mtxb[16];
	int evc_no;
	int hct;
	int ct0;
	int ct1;
	int keyf_no;
	float frm;
	float spd;
	float pxn;
	float pyn;
	float pzn;
	int axn;
	int ayn;
	int azn;
	int pe_ax;
	int pe_pers;
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	float ips[3][20];
	float ian[3][20];
	float ipf[3][20];
	float icr[3][20];
};

struct _anon36
{
	float px;
	float py;
	float pz;
	float vx;
	float vy;
	float vz;
};

struct _anon37
{
	unsigned int type;
	unsigned int reserved[3];
	unsigned char is_root;
	unsigned char area_code;
	unsigned char connector_dir[2];
	char product_name[32];
	char license[64];
	unsigned short stdby_pow;
	unsigned short max_pow;
};

struct _anon38
{
	int lsrc;
	float iamb;
	float idif;
	float ispc;
	float nrang;
	float frang;
	void* func;
	int iang;
	int oang;
	_anon24 argb;
};

struct _anon39
{
	_anon0 c;
	float r;
};

struct _anon40
{
	_anon0 c1;
	_anon0 c2;
	float r;
};

struct _anon41
{
	float px;
	float py;
	float pz;
	float ox;
	float oy;
	float oz;
};*/

void bhEff_SetPtcl(BH_PWORK* epw, NJS_POINT3* pos, int tex_id);
void bhEff_SetPtcl1(BH_PWORK* epw, NJS_POINT3* pos, int tex_id, int wcnt);
void bhEff_SetPtcl2(NJS_POINT3* pos, float mtx[16]);
void bhEff_SetPtcl2V(NJS_POINT3* pos, NJS_POINT3* dv, int wcnt);
void bhEff_SetBlood5(NJS_POINT3* pos, NJS_POINT3* vec, float size, int col);
void bhEff_Sub350(O_WRK* op);
void bhEff_Sub351(O_WRK* op);
void bhEff_Sub352(O_WRK* op);
void bhEff_Sub353(O_WRK* op);
void bhEff_Sub354(O_WRK* op);
void bhEff_Sub355(O_WRK* op);
void bhEff_Sub356(O_WRK* op);
void bhEff_Sub357();
void bhEff_Sub360(O_WRK* op);
void bhEff_Sub361(O_WRK* op);
void bhEff_Sub362(O_WRK* op);
void bhEff_Sub363(O_WRK* op);
void bhEff_Sub364(O_WRK* op);
void bhEff_Sub365(O_WRK* op);
void bhEff_Sub366(O_WRK* op);
void bhEff_Sub367(O_WRK* op);
void bhEff_Sub368(O_WRK* op);
void bhEff_Sub369(O_WRK* op);
void bhEff_Sub370(O_WRK* op);
void bhEff_Sub371(O_WRK* op);
void bhEff_Sub372(O_WRK* op);
void bhEff_Sub373(O_WRK* op);
void bhEff_Sub398(O_WRK* op);
O_WRK* bhEff_AllocOwork();
void bhEff_PtclSpriteDraw(O_WRK* op);
void bhEff_LineDraw(O_WRK* op);
void bhEff_SetSprite(O_WRK* op, UV_WORK* uvp, int mode);
void bhEff_SetSpriteAnime(O_WRK* op, EFF_ANIM* eff_anim, UV_WORK* uvp, int mode);
void bhEff_3DSpriteDraw(O_WRK* op);
void bhEff_ModelDraw(O_WRK* op);

#endif
