#ifndef _EFFSUB0_H_
#define _EFFSUB0_H_

#include "types.h"

typedef struct EFF0UVWHUC 
{
    // total size: 0x4
    unsigned char u; // offset 0x0, size 0x1
    unsigned char v; // offset 0x1, size 0x1
    unsigned char w; // offset 0x2, size 0x1
    unsigned char h; // offset 0x3, size 0x1
} EFF0UVWHUC;

/*typedef struct npobj;
typedef struct _anon0;
typedef struct _anon1;
typedef struct _anon2;
typedef struct _anon3;
typedef struct _anon4;
typedef struct _anon5;
typedef struct _anon6;
typedef struct tagEFF0UV;
typedef struct _anon7;
typedef struct _anon8;
typedef struct tagEFF0UVWHUC;
typedef struct _anon9;
typedef struct _anon10;
typedef struct _anon11;
typedef struct _anon12;
typedef struct _anon13;
typedef struct _anon14;
typedef struct _anon15;
typedef struct _anon16;
typedef struct _anon17;
typedef struct _anon18;
typedef struct _anon19;
typedef struct _anon20;
typedef struct BH_PWORK;
typedef struct _anon21;
typedef struct _anon22;
typedef struct _anon23;
typedef struct _anon24;
typedef struct _anon25;
typedef struct _anon26;
typedef struct _anon27;
typedef struct _anon28;
typedef struct _anon29;
typedef struct _anon30;
typedef struct _anon31;
typedef struct _anon32;
typedef struct _anon33;
typedef struct _anon34;

typedef void(*type_108)(void*);

typedef float type_0[16];
typedef unsigned int type_1[4];
typedef _anon3 type_2[1];
typedef _anon0* type_3[512];
typedef int type_4[24];
typedef _anon0* type_5[32];
typedef _anon1* type_6[16];
typedef _anon0* type_7[32];
typedef _anon0* type_8[512];
typedef _anon1* type_9[16][16];
typedef _anon1* type_10[16][16][100];
typedef char type_11[8];
typedef _anon0* type_12[32];
typedef _anon3 type_13[13];
typedef _anon3 type_14[12];
typedef _anon0* type_15[512];
typedef tagEFF0UV type_16[15];
typedef _anon1* type_17[1300];
typedef unsigned int type_18[4];
typedef unsigned int type_19[4][10];
typedef char type_20[32];
typedef int type_21[3];
typedef _anon0* type_22[512];
typedef _anon3 type_23[5];
typedef _anon1* type_24[200];
typedef _anon3 type_25[16];
typedef short type_26[32];
typedef _anon15 type_27[1];
typedef _anon0* type_28[128];
typedef unsigned int type_29[1];
typedef int type_30[26];
typedef _anon6 type_31[256];
typedef _anon1* type_32[8];
typedef int* type_33[16];
typedef _anon0* type_34[128];
typedef npobj* type_35[16];
typedef _anon3 type_36[6];
typedef _anon0* type_37[128];
typedef int type_38[4];
typedef _anon1* type_39[16];
typedef unsigned int type_40[4];
typedef _anon9 type_41[16];
typedef _anon0* type_42[512];
typedef _anon3 type_43[5];
typedef _anon3 type_44[2];
typedef _anon3 type_45[11];
typedef char type_46[256];
typedef float type_47[4];
typedef float type_48[4];
typedef float type_49[4];
typedef _anon5* type_50[128];
typedef float type_51[3];
typedef unsigned char type_52[64];
typedef float type_53[3][20];
typedef int type_54[10];
typedef _anon3 type_55[5];
typedef _anon0 type_56[0];
typedef float type_57[3];
typedef float type_58[3][20];
typedef float type_59[3];
typedef float type_60[3][20];
typedef char type_61[8];
typedef float type_62[3];
typedef float type_63[3][20];
typedef void* type_64[2];
typedef _anon3 type_65[5];
typedef _anon1* type_66[256];
typedef int type_67[4];
typedef unsigned char* type_68[256];
typedef _anon3* type_69[6];
typedef _anon24 type_70[11];
typedef unsigned int type_71[2];
typedef short type_72[256];
typedef unsigned char type_73[10];
typedef _anon3 type_74[13];
typedef _anon3 type_75[16];
typedef _anon3 type_76[5];
typedef _anon21 type_77[4];
typedef float type_78[3];
typedef short type_79[256];
typedef int type_80[3];
typedef int type_81[8];
typedef float type_82[3];
typedef _anon1* type_83[256];
typedef _anon8 type_84[256];
typedef tagEFF0UV* type_85[4];
typedef _anon15 type_86[450];
typedef _anon3 type_87[11];
typedef unsigned char type_88[10];
typedef _anon3 type_89[11];
typedef _anon23 type_90[16];
typedef short type_91[256];
typedef char type_92[3];
typedef int type_93[64];
typedef _anon9 type_94[450];
typedef _anon3 type_95[11];
typedef _anon27 type_96[4];
typedef _anon3 type_97[11];
typedef _anon2 type_98[4];
typedef int type_99[450];
typedef int type_100[10];
typedef unsigned int type_101[8];
typedef unsigned char type_102[450];
typedef _anon3* type_103[10];
typedef _anon3 type_104[11];
typedef unsigned int type_105[4];
typedef char type_106[16];
typedef char type_107[4];
typedef unsigned int type_109[32];
typedef unsigned int type_110[16];
typedef tagEFF0UVWHUC type_111[20];
typedef _anon3 type_112[15];
typedef _anon28 type_113[64];
typedef unsigned int type_114[16];
typedef _anon28 type_115[64];
typedef unsigned int type_116[32];
typedef _anon3 type_117[8];
typedef _anon28 type_118[64];
typedef unsigned int type_119[16];
typedef unsigned int type_120[3];
typedef BH_PWORK* type_121[16];
typedef unsigned int type_122[8];
typedef _anon3 type_123[18];
typedef unsigned int type_124[1];
typedef unsigned int type_125[384];
typedef unsigned int type_126[2];
typedef unsigned char type_127[2];
typedef int* type_128[16];
typedef unsigned int type_129[4];
typedef char type_130[32];
typedef npobj* type_131[16];
typedef _anon3 type_132[8];
typedef char type_133[64];
typedef _anon1* type_134[16];
typedef char type_135[4];
typedef tagEFF0UV type_136[10];
typedef _anon3 type_137[25];
typedef _anon9 type_138[16];
typedef float type_139[3];
typedef float type_140[3][4];
typedef short type_141[4];
typedef _anon3 type_142[14];
typedef float type_143[3][4][2];
typedef unsigned char type_144[4];
typedef _anon25 type_145[16];
typedef _anon3 type_146[7];
typedef _anon3 type_147[11];
typedef unsigned int type_148[32];
typedef _anon3 type_149[8];
typedef _anon24 type_150[32];
typedef tagEFF0UVWHUC* type_151[3];
typedef _anon0* type_152[512];
typedef _anon3 type_153[27];
typedef _anon0* type_154[128];
typedef _anon3 type_155[14];
typedef _anon0* type_156[512];
typedef unsigned char type_157[64];
typedef _anon3 type_158[5];
typedef _anon0* type_159[512];
typedef _anon3 type_160[11];

struct npobj
{
	unsigned int evalflags;
	_anon22* model;
	float pos[3];
	int ang[3];
	float scl[3];
	npobj* child;
	npobj* sibling;
};

struct _anon0
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	char flr_no;
	char flr_nob;
	unsigned char mdlver;
	unsigned char param;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	int ax;
	int ay;
	int az;
	float ar;
	float aw;
	float ah;
	float ad;
	float car;
	float cah;
	float pxb;
	float pyb;
	float pzb;
	int axb;
	int ayb;
	int azb;
	float gpx;
	float gpy;
	float gpz;
	float lox;
	float loy;
	float loz;
	float aox;
	float aoy;
	float aoz;
	float spd;
	unsigned int flg2;
	unsigned int mdflg;
	unsigned int stflg;
	unsigned int Dummy3;
	int draw_tp;
	int mdl_n;
	void* mskp;
	unsigned int Dummy[1];
	int* skp[16];
	npobj* mbp[16];
	_anon1* txp[16];
	_anon9 mdl[16];
	_anon9* mlwP;
	unsigned int mdl_no;
	int lkono;
	unsigned char* lkwkp;
	unsigned char* exp0;
	unsigned char* exp1;
	unsigned char* exp2;
	unsigned char* exp3;
	unsigned char mtxbuf[64];
	float mtx[16];
	npobj* obj_a;
	npobj* obj_b;
	float shp_ct;
	char clp_jno[8];
	int lok_jno;
	_anon5* mnwP;
	_anon5* mnwPb;
	unsigned int mtn_attr;
	unsigned int mtn_no;
	int frm_no;
	unsigned int frm_mode;
	int hokan_rate;
	unsigned int hokan_count;
	unsigned int hokan_ctbak;
	int mtn_add;
	unsigned int mtn_md;
	unsigned char* mtn_tp;
	int axp;
	int ayp;
	int azp;
	short psh_ct;
	short psh_idx;
	int idx_ct;
	int mtn_chk;
	float ofx;
	float ofy;
	float ofz;
	float sx;
	float sy;
	float sz;
	float sxb;
	float syb;
	float szb;
	float xn;
	float yn;
	float zn;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	unsigned char* objbak;
	_anon33 cspr;
	int pn;
	_anon27* pvp;
	_anon2* tvp;
	_anon27 pv[4];
	_anon2 tv[4];
	int bl_src;
	int bl_dst;
	int ani_ct;
	int tex_id;
	int aspd;
	unsigned int gidx;
	int bank;
	char jno[16];
	char hide[4];
	void(*func)(void*);
	int idx;
	int Dummy2;
};

struct _anon1
{
	_anon15* textures;
	unsigned int nbTexture;
};

struct _anon2
{
	float x;
	float y;
	float z;
	float u;
	float v;
	unsigned int col;
};

struct _anon3
{
	float u;
	float v;
	float xs;
	float ys;
};

struct _anon4
{
	unsigned int ssd_ver;
	unsigned int ssd_flg;
	unsigned int ssd_reserve;
	char keytype;
	char adjust_x;
	char adjust_y;
	char vibration;
	int best_tm[8];
	unsigned int sys_partid;
	unsigned int itm_partid;
	unsigned int fil_partid;
	unsigned int dor_partid;
	unsigned int ss_flg;
	int pdm_no;
	unsigned int typ_flg;
	unsigned short typ_md0;
	unsigned short typ_md1;
	void* typ_exp;
	unsigned int tk_flg;
	unsigned int ts_flg;
	unsigned int gm_flg;
	unsigned int st_flg;
	unsigned int cb_flg;
	unsigned int rm_flg;
	unsigned int pt_flg;
	unsigned int sp_flg;
	unsigned int ef_flg;
	unsigned int error;
	unsigned int version;
	int save_ct;
	char ply_id;
	char stg_no;
	char rom_no;
	char rcase;
	char pos_no;
	char cut_no;
	char flr_no;
	char reserve0;
	int gm_mode;
	unsigned int ev_flg[32];
	unsigned int it_flg[16];
	unsigned int ic_flg[16];
	unsigned int ed_flg[32];
	unsigned int ky_flg[16];
	unsigned int mp_flg[8];
	unsigned int itm[384];
	unsigned int ply_stflg[4];
	_anon24 ply_pos;
	int ply_ang;
	char ply_wno[4];
	short ply_hp[4];
	unsigned char evt_posno[4];
	int time;
	int stv_tm;
	short spray_ct;
	short retry_ct;
	short clear_ct;
	short reserve1;
	unsigned int save_end;
	char stg_nob;
	char rom_nob;
	char pos_nob;
	char rcase_b;
	unsigned int en_flg[4];
	_anon1* et_lp[16][16][100];
	_anon1* ot_lp[1300];
	_anon1* it_lp[200];
	int eft_n;
	_anon1* eft_lp[8];
	int loop_ct;
	int loop_now;
	int cng_pid;
	_anon10* p1per;
	_anon10* p2per;
	_anon10* kbper;
	_anon10* msper;
	_anon10 ms_per;
	int pad_port;
	unsigned int pad_on;
	unsigned int pad_oncpy;
	unsigned int pad_ps;
	unsigned int pad_rs;
	unsigned int pad_old;
	unsigned int pad_onb;
	unsigned int pad_psb;
	unsigned int pad_oldb;
	short pad_ax;
	short pad_ay;
	short pad_dx;
	short pad_dy;
	unsigned short pad_ar;
	unsigned short pad_al;
	int fixcno;
	int fixkno;
	unsigned int exm_attr;
	short evc_no;
	short evc_kn;
	short evc_ono;
	short evc_okn;
	int evc_sc;
	unsigned char mn_mode0;
	unsigned char mn_mode1;
	unsigned char mn_mode2;
	unsigned char mn_mode3;
	unsigned char mn_md0;
	unsigned char mn_md1;
	unsigned char mn_md2;
	unsigned char mn_md3;
	int mn_setct;
	unsigned int mn_stack[8];
	unsigned int sdm_flg;
	unsigned int sdm_mode;
	unsigned char* ltc_bp;
	unsigned int ltc_tsbak;
	int ewk_n;
	unsigned int enow;
	unsigned int onow;
	unsigned int efnow;
	int vsyc_ct;
	int vsyc_flg;
	int fog_ct;
	int bcl_ct;
	int gfrm_ct;
	int gframe;
	int eor_ct;
	unsigned int pfm_cts;
	int evt_tmd;
	int evt_tim;
	int evt_tdg;
	int evt_fcd;
	unsigned int evt_fcdct;
	unsigned int fsize;
	unsigned int rdtsz;
	unsigned char* memp;
	unsigned char* mempb;
	unsigned char* endp;
	unsigned char* rdtp;
	unsigned char* plmdlp;
	unsigned char* lmmdlp;
	unsigned char* wrmdlp;
	unsigned char* wlmdlp;
	unsigned char* plmthp;
	unsigned char* plbmtp;
	unsigned char* plwmtp;
	unsigned char* plzmtp;
	unsigned char* plemtp;
	unsigned char* plexwp;
	unsigned char* plhdwp;
	unsigned char* pletcp;
	unsigned char* subtxp;
	unsigned char* doordp;
	unsigned char* sbs_sp;
	_anon0* obwp;
	_anon0* itwp;
	_anon5* emtp[128];
	_anon5* rmthp;
	unsigned char* mspp;
	unsigned char* lspp;
	unsigned int* mes_ip;
	unsigned int* mes_sp;
	void* mes_tp;
	short txr_n;
	short txr_ct;
	_anon1* txlp[256];
	unsigned char* txdp[256];
	short txloff[256];
	short txb_ct;
	short txb_n;
	short txb[256];
	_anon1* txblp[256];
	_anon8 txbp[256];
	unsigned char* ef_psp;
	_anon15 ef_tex[450];
	_anon1 ef_tlist;
	_anon12 ef;
	short efid[256];
	_anon9 efm[450];
	int ef_ct;
	int ef_ctb;
	int ef_extn;
	int ef_tn[450];
	unsigned char ef_pbkb[450];
	int ef_pbnk;
	int ef_slow;
	int ef_ctrn;
	int yk_ct;
	int mg_ct;
	int bl_ct;
	int windr;
	float winds;
	int windrb;
	float windsb;
	unsigned int thunder;
	float gas_py;
	int en_objn;
	BH_PWORK* en_obj[16];
	int ef_poln;
	int ef_mdfn;
	int ef_linn;
	int ef_ntxn;
	int ef_trsn;
	int ef_pncn;
	int ef_opqn;
	int ef_thln;
	int ef_ntx2dn;
	int ef_trs2dn;
	int ef_pnc2dn;
	int ef_fncn;
	_anon0* ef_pol[512];
	_anon0* ef_mdf[128];
	_anon0* ef_lin[512];
	_anon0* ef_ntx[512];
	_anon0* ef_trs[512];
	_anon0* ef_pnc[512];
	_anon0* ef_opq[512];
	_anon0* ef_thl[512];
	_anon0* ef_ntx2d[128];
	_anon0* ef_trs2d[128];
	_anon0* ef_pnc2d[128];
	_anon0* ef_fnc[512];
	int ob_nlgn;
	int ob_hlgn;
	int ob_spcn;
	_anon0* ob_nlg[32];
	_anon0* ob_hlg[32];
	_anon0* ob_spc[32];
	unsigned int ren_gid;
	_anon13 ren_info;
	_anon15 ren_tex[1];
	_anon1 ren_tlist;
	_anon6 rpb[256];
	int ren_n;
	int ren_idx[4];
	int wt_nbpt;
	float wt_px;
	float wt_pz;
	int wt_xp;
	int wt_zp;
	int wt_minx;
	int wt_minz;
	int wt_maxx;
	int wt_maxz;
	unsigned char* wt_wvp;
	_anon30 mr_pl;
	unsigned char* zan_memp;
	unsigned char* zanp;
	_anon17* lgtp;
	float lg_vx;
	float lg_vy;
	float lg_vz;
	float lg_r;
	float lg_g;
	float lg_b;
	int lg_pnt;
	_anon21 lg_ptb[4];
	int mes_idx;
	unsigned int* mes_dp;
	int mes_ct;
	int mes_tim;
	int mes_fls;
	int mes_sel;
	int mes_seln;
	_anon23 mes_sps[16];
	int rt_sp;
	unsigned char* rt_wp;
	unsigned char* rt_dp;
	unsigned char* rt_nw;
	unsigned char* rt_nx;
	float* rt_ln;
	BH_PWORK* plp;
	_anon28* pl_htp;
	int costume;
	_anon24 hd_pos;
	_anon24 apos;
	_anon28* ahtp;
	int mwal_n;
	int metc_n;
	int mflr_n;
	_anon28 mwalp[64];
	_anon28 metcp[64];
	_anon28 mflrp[64];
	int dla_n;
	_anon28* htp;
	int psh_snd;
	int fog_cngct;
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	float fade_ct;
	float fade_hkn;
	float fade_ao;
	float fade_an;
	float fade_ap;
	float fade_ro;
	float fade_rn;
	float fade_rp;
	float fade_go;
	float fade_gn;
	float fade_gp;
	float fade_bo;
	float fade_bn;
	float fade_bp;
	unsigned int fade_pbk;
	unsigned short ssv_md0;
	unsigned short ssv_md1;
	int ssv_tim;
	float ssv_ct;
	float ssv_hkn;
	float ssv_ao;
	float ssv_an;
	float ssv_ap;
	short fil_no;
	short fil_rt;
	float rvf_sc;
	float rvf_sn;
	unsigned int rvfc[4];
	float cine_an;
	float cine_ap;
	unsigned int sco_flg;
	float amb_r[4];
	float amb_g[4];
	float amb_b[4];
	int sb_id;
	int sb_cmd;
	int sb_rdid;
	int sb_rdsz;
	void* sb_rdp;
	void* sb_mlb;
	void* sb_ppp;
	_anon1* sb_tlist;
	int ddmd;
	_anon11 door;
	int mpmd;
	int mp_prm[4];
	unsigned short gov_md0;
	unsigned short gov_md1;
	int gov_ct;
	void* gov_exp;
	unsigned int com_flg;
	unsigned short com_md0;
	unsigned short com_md1;
	unsigned int com_num;
	void* com_exp;
	short ond_tnm;
	short ond_ud;
	char ond_cx;
	char ond_n[3];
	unsigned char ufo_md;
	unsigned char ufo_flg;
	short ufo_oidx;
	_anon24 ufo_pos;
	unsigned int opt_flg;
	unsigned short opt_md0;
	unsigned short opt_md1;
	void* opt_exp;
	unsigned int etc_idx;
	unsigned int flr_idx;
	int mvi_no;
	int mvi_tp;
	unsigned short mvi_md;
	unsigned short mvi_flg;
	unsigned int mvi_tsb;
	unsigned int mvi_spb;
	unsigned char* mvi_memp;
	unsigned int dcg_tkbak;
	unsigned int dcg_tsbak;
	unsigned int pau_spbak;
	unsigned int pau_pad_on;
	unsigned int pau_pad_ps;
	unsigned int pau_pad_old;
	unsigned char* pdm_dp;
	unsigned char* pdm_pd;
	int pdm_keytpb;
	int gat_ct;
	_anon25 gatc[16];
	int ght_ct;
	unsigned int ghtc[32];
	_anon24 ghtp[32];
	unsigned short db_md0;
	unsigned short db_md1;
	char db_stgno;
	char db_romno;
	char db_rcase;
	char db_muteki;
	short db_px;
	short db_py;
	int db_mes;
	int calc_v;
	unsigned int brkfg;
	char brkfg_typ[32];
	short brkfg_bit[32];
	unsigned int brkfg_tkb;
	unsigned int brkfg_tsb;
	int brkfg_ct;
	unsigned int bmt_size;
	unsigned int lmt_size;
	unsigned int emt_size;
	unsigned int wmt_size;
	char mes[256];
	float sfx;
	float sfy;
	float sfxn;
	float sfyn;
	float sfct;
};

struct _anon5
{
	unsigned int flg;
	unsigned int obj_num;
	unsigned int frm_num;
	void* datP;
	_anon14* md2P;
	unsigned short* atrP;
};

struct _anon6
{
	float x;
	float y;
	float z;
	float u;
	float v;
	unsigned int bcol;
	unsigned int ocol;
};

struct tagEFF0UV
{
	short u;
	short v;
};

struct _anon7
{
	unsigned int Type;
	unsigned int BitDepth;
	unsigned int PixelFormat;
	unsigned int nWidth;
	unsigned int nHeight;
	unsigned int TextureSize;
	unsigned int fSurfaceFlags;
	unsigned int* pSurface;
	unsigned int* pVirtual;
	unsigned int* pPhysical;
};

struct _anon8
{
	unsigned char* adr;
	unsigned int gidx;
	unsigned int attr;
	unsigned int w;
	unsigned int h;
};

struct tagEFF0UVWHUC
{
	unsigned char u;
	unsigned char v;
	unsigned char w;
	unsigned char h;
};

struct _anon9
{
	unsigned int flg;
	unsigned int obj_num;
	void* datP;
	npobj* objP;
	_anon1* texP;
	_anon19* owP;
};

struct _anon10
{
	unsigned int id;
	unsigned int support;
	unsigned int on;
	unsigned int off;
	unsigned int press;
	unsigned int release;
	unsigned short r;
	unsigned short l;
	short x1;
	short y1;
	short x2;
	short y2;
	char* name;
	void* extend;
	unsigned int old;
	_anon31* info;
};

struct _anon11
{
	unsigned int flg;
	char stg_no;
	char rom_no;
	unsigned char pos_no;
	unsigned char dor_tp;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
};

struct _anon12
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	short flr_no;
	unsigned short mdlver;
	float px;
	float py;
	float pz;
	float sx;
	float sy;
	float sz;
	short ay;
	short ax;
};

struct _anon13
{
	void* texaddr;
	_anon7 texsurface;
};

struct _anon14
{
	void* p[2];
};

struct _anon15
{
	void* filename;
	unsigned int attr;
	unsigned int texaddr;
};

struct _anon16
{
	short jnt_a;
	short jnt_b;
	int cap_r;
};

struct _anon17
{
	unsigned int flg;
	unsigned int type;
	int aspd;
	int lkflg;
	int lkno;
	int lkono;
	int lsrc;
	float px;
	float py;
	float pz;
	float lx;
	float ly;
	float lz;
	float vx;
	float vy;
	float vz;
	float spc;
	float dif;
	float amb;
	float r;
	float g;
	float b;
	float nr;
	float fr;
	int iang;
	int oang;
	int ax;
	int ay;
	int az;
	unsigned int mode;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	float wpx;
	float wpy;
	float wpz;
	float wvx;
	float wvy;
	float wvz;
	float wspc;
	float wdif;
	float wamb;
	float wr;
	float wg;
	float wb;
	float wnr;
	float wfr;
	int wiang;
	int woang;
	int wax;
	int way;
	int waz;
	unsigned char* lkwkp;
	unsigned char* exp;
	_anon20* light;
};

struct _anon18
{
	float a;
	float r;
	float g;
	float b;
};

struct _anon19
{
	unsigned int flg;
	int dmy;
	unsigned int dummy[2];
	float mtx[16];
};

struct _anon20
{
	float mtrx[16];
	_anon24 pnt;
	_anon24 vctr;
	int stat;
	int reserve;
	_anon26 ltcal;
	_anon32 attr;
};

struct BH_PWORK
{
	unsigned int flg;
	unsigned short id;
	unsigned short type;
	char flr_no;
	char flr_nob;
	unsigned char mdlver;
	unsigned char param;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	int ax;
	int ay;
	int az;
	float ar;
	float aw;
	float ah;
	float ad;
	float car;
	float cah;
	float pxb;
	float pyb;
	float pzb;
	int axb;
	int ayb;
	int azb;
	float gpx;
	float gpy;
	float gpz;
	float lox;
	float loy;
	float loz;
	float aox;
	float aoy;
	float aoz;
	float spd;
	unsigned int flg2;
	unsigned int mdflg;
	unsigned int stflg;
	unsigned int Dummy3;
	int draw_tp;
	int mdl_n;
	void* mskp;
	unsigned int Dummy[1];
	int* skp[16];
	npobj* mbp[16];
	_anon1* txp[16];
	_anon9 mdl[16];
	_anon9* mlwP;
	unsigned int mdl_no;
	int lkono;
	unsigned char* lkwkp;
	unsigned char* exp0;
	unsigned char* exp1;
	unsigned char* exp2;
	unsigned char* exp3;
	unsigned char mtxbuf[64];
	float mtx[16];
	npobj* obj_a;
	npobj* obj_b;
	float shp_ct;
	char clp_jno[8];
	int lok_jno;
	_anon5* mnwP;
	_anon5* mnwPb;
	unsigned int mtn_attr;
	unsigned int mtn_no;
	int frm_no;
	unsigned int frm_mode;
	int hokan_rate;
	unsigned int hokan_count;
	unsigned int hokan_ctbak;
	int mtn_add;
	unsigned int mtn_md;
	unsigned char* mtn_tp;
	int axp;
	int ayp;
	int azp;
	short psh_ct;
	short psh_idx;
	int idx_ct;
	int mtn_chk;
	float ofx;
	float ofy;
	float ofz;
	float sx;
	float sy;
	float sz;
	float sxb;
	float syb;
	float szb;
	float xn;
	float yn;
	float zn;
	int ct0;
	int ct1;
	int ct2;
	int ct3;
	int wpnr_no;
	int wpnl_no;
	unsigned int at_flg;
	_anon34 watr;
	_anon16* cpcl;
	short wax;
	short way;
	short waz;
	short waxp;
	short wayp;
	short wazp;
	int hp;
	int dam[64];
	int djnt_no;
	int cpcl_no;
	int dax;
	int day;
	float dpx;
	float dpy;
	float dpz;
	float dvx;
	float dvy;
	float dvz;
	int flr_snd;
	int ko_num;
	int footeff;
	int src_no;
	unsigned char* kdnp;
	int kdnidx;
	void* dan_ap;
	unsigned int comb_flg;
	unsigned int comb_wep;
	int comb_pnt;
	int comb_timeout;
	int total_dam;
	unsigned int Dummy2[2];
};

struct _anon21
{
	_anon24 ps;
	float nr;
	float fr;
	float cr;
	float cg;
	float cb;
};

struct _anon22
{
	int* vlist;
	short* plist;
	_anon24 center;
	float r;
};

struct _anon23
{
	float x;
	float y;
};

struct _anon24
{
	float x;
	float y;
	float z;
};

struct _anon25
{
	_anon24 c1;
	_anon24 c2;
	float r1;
	float r2;
};

struct _anon26
{
	float ratten;
	float ipd;
	float nrr;
	float frr;
	float cosi;
	float cose;
	float idev;
	float odev;
	float rate;
	float intns;
	int exp;
	int reserve;
	_anon24 lpnt;
	_anon24 lvctr;
	_anon24 lmvctr;
	_anon18 atten;
	_anon18 amb;
	_anon18 dif;
	_anon18 spc;
	_anon18 mamb;
	_anon18 mdif;
	_anon18 mspc;
};

struct _anon27
{
	float x;
	float y;
	float z;
	unsigned int col;
};

struct _anon28
{
	unsigned char flg;
	unsigned char type;
	unsigned char id;
	char flr_no;
	unsigned int attr;
	float px;
	float py;
	float pz;
	float w;
	float h;
	float d;
	unsigned char prm0;
	unsigned char prm1;
	unsigned char prm2;
	unsigned char prm3;
};

struct _anon29
{
	unsigned int flg;
	int camver;
	unsigned char mode0;
	unsigned char mode1;
	unsigned char mode2;
	unsigned char mode3;
	float px;
	float py;
	float pz;
	float vx;
	float vy;
	float vz;
	float wpx;
	float wpy;
	float wpz;
	float plx;
	float ply;
	float plz;
	float pxp;
	float pyp;
	float pzp;
	float ofx;
	float ofy;
	float ofz;
	int ax;
	int ay;
	int az;
	int axp;
	int ayp;
	int azp;
	float ln;
	float pln;
	float xr;
	float xn;
	float yr;
	float yn;
	int pers;
	int ppers;
	int ncut;
	int ocut;
	unsigned int ocflg;
	unsigned int attr;
	float mtx[16];
	float mtxb[16];
	int evc_no;
	int hct;
	int ct0;
	int ct1;
	int keyf_no;
	float frm;
	float spd;
	float pxn;
	float pyn;
	float pzn;
	int axn;
	int ayn;
	int azn;
	int pe_ax;
	int pe_pers;
	unsigned int fog_col;
	float fog_nr;
	float fog_fr;
	float ips[3][20];
	float ian[3][20];
	float ipf[3][20];
	float icr[3][20];
};

struct _anon30
{
	float px;
	float py;
	float pz;
	float vx;
	float vy;
	float vz;
};

struct _anon31
{
	unsigned int type;
	unsigned int reserved[3];
	unsigned char is_root;
	unsigned char area_code;
	unsigned char connector_dir[2];
	char product_name[32];
	char license[64];
	unsigned short stdby_pow;
	unsigned short max_pow;
};

struct _anon32
{
	int lsrc;
	float iamb;
	float idif;
	float ispc;
	float nrang;
	float frang;
	void* func;
	int iang;
	int oang;
	_anon18 argb;
};

struct _anon33
{
	_anon24 c;
	float r;
};

struct _anon34
{
	_anon24 c1;
	_anon24 c2;
	float r;
};*/

int setentry(unsigned short id, unsigned short type, O_WRK* op);
void effinit(O_WRK* op);
void effset(O_WRK* op, UV_WORK* uvp, unsigned short num);
void getuv(unsigned char type, O_WRK* op);
void bhEff150(O_WRK* op);
void bhEff151(O_WRK* op);
void bhEff152(O_WRK* op);
void bhEff153(O_WRK* op);
void bhEff154(O_WRK* op);
void bhEff155(O_WRK* op);
void bhEff156(O_WRK* op);
void bhEff157(O_WRK* op);
void bhEff158(O_WRK* op);
void bhEff159(O_WRK* op);
void bhEff160(O_WRK* op);
void bhEff161(O_WRK* op);
void bhEff162(O_WRK* op);
void bhEff163(O_WRK* op);
void bhEff164(O_WRK* op);
void bhEff165(O_WRK* op);
void bhEff166(O_WRK* op);
void bhEff167(O_WRK* op);
void bhEff168(O_WRK* op);
void bhEff169(O_WRK* op);
void bhEff170(O_WRK* op);
void bhEff171(O_WRK* op);
void bhEff172(O_WRK* op);
void bhEff173(O_WRK* op);
void bhEff174();
void bhEff175(O_WRK* op);
void bhEff176(O_WRK* op);
void bhEff177(O_WRK* op);
void bhEff178(O_WRK* op);
void bhEff179(O_WRK* op);
void bhEff180(O_WRK* op);
void bhEff181(O_WRK* op);
void bhEff182(O_WRK* op);
void bhEff183(O_WRK* op);
void bhEff184(O_WRK* op);
void bhEff185(O_WRK* op);
void bhEff186(O_WRK* op);
void bhEff187(O_WRK* op);
void bhEff188(O_WRK* op);
void bhEff189(O_WRK* op);
void bhEff190(O_WRK* op);
void bhEff191(O_WRK* op);
void bhEff192(O_WRK* op);
void bhEff193(O_WRK* op);
void bhEff194(O_WRK* op);
void bhEff195(O_WRK* op);
void bhEff196(O_WRK* op);
void bhEff197();
void bhEff198(O_WRK* op);
void bhEff199();

#endif
